Added linux-live 5.0.2.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/initrd/initrd_create b/initrd/initrd_create
--- a/initrd/initrd_create
+++ b/initrd/initrd_create
@@ -1,89 +1,135 @@
 #!/bin/bash
 #
-# initrd_create:  make initrd rootdisk
+# initrd_create:  make initrd rootdisk by using busybox
 #
-# Author:	  Tomas Matejicek <http://www.linux-live.org>
+# Author:	  Tomas M. <http://www.linux-live.org>
 
 . ../config || exit 1
-. ./liblinuxlive || exit 1 
 
-KERNEL=`/bin/uname -r`
+# rcopy is a recursive cp, which copies also symlink's real source
+# $1 = source (may be a regular file or symlink)
+# $2 = target PARENT
+#
+rcopy()
+{
+   if [ -L "$1" ]; then
+      REALPATH="`readlink -f \"$1\"`"
+      cp --parent -R "$REALPATH" "$2"
+      ln -sf "$REALPATH" "$2/$1"
+   else
+      cp --parent -R "$1" "$2"
+   fi
+   if [ "$?" -ne 0 ]; then
+      echo "---------------------------"
+      echo "Error occured while trying to copy \"$1\" to \"$2\""
+      echo "nevertheless your LiveCD may still work."
+      echo "Possible reason: not enough free space in initrd or source doesn't exist"
+      echo "---------------------------"
+   fi
+}
 
-echo "creating empty image file initrd.img..."
+# copy file/dir only if it exists, else skip with no error
+# $1 = source (may not exist)
+# $2 = target PARENT
+#
+rcopy_ex()
+{
+   if [ -a "$1" ]; then
+      rcopy "$1" "$2"
+   fi
+}
+
+##################################################
+# Create INITRD image now:
+
+if [ ! -d "kernel-modules/$KERNEL" ]; then
+   echo "The directory kernel-modules/$KERNEL doesn't exist. Please create it and copy"
+   echo "squashFS and unionFS modules for your kernel version to it."
+   exit 1
+fi
+
+echo "creating empty image file initrd.img"
 dd if=/dev/zero of=$INITRDIMG bs=1024 count=$RAM0SIZE >/dev/null 2>/dev/null
 
-echo "making filesystem..."
-mkfs -t ext2 -F -m 0 -i 1024 $INITRDIMG >/dev/null 2>/dev/null
+echo "making filesystem"
+mkfs -t ext2 -F -m 0 -b 1024 -i 1024 $INITRDIMG 2>/dev/null >/dev/null
 
-echo "creating empty directory $MOUNTDIR..."
+echo "creating empty directory $MOUNTDIR"
 rm -Rf $MOUNTDIR
 mkdir $MOUNTDIR
 
-echo "mounting initrd.img to it..."
+echo "mounting initrd.img to it"
 mount -o loop $INITRDIMG $MOUNTDIR
+if [ "$?" -ne 0 ]; then
+   echo "Error mounting initrd! Not enough free loop devices?"
+   exit 1
+fi
 
-echo "creating directories..."
+echo "creating directories"
 rmdir $MOUNTDIR/lost+found
-mkdir -p $MOUNTDIR/{etc,dev,bin,mnt,proc,sbin,lib,tmp,usr/bin,usr/sbin,var/log}
+mkdir -p $MOUNTDIR/{etc,dev,bin,mnt,proc,lib,sys,tmp,var/log}
 
-echo "copying files to the rootdisk (this may take some time)..."
+echo "creating some essential devices in rootdisk"
+mknod $MOUNTDIR/dev/console c 5 1
+mknod $MOUNTDIR/dev/null c 1 3
+mknod $MOUNTDIR/dev/ram b 1 1
+mknod $MOUNTDIR/dev/systty c 4 0
+mknod $MOUNTDIR/dev/tty c 5 0
+mknod $MOUNTDIR/dev/tty1 c 4 1
+
+loops=255
+while [ $loops -ge 0 ]; do
+   mknod $MOUNTDIR/dev/loop$loops b 7 $loops
+   loops=$(($loops-1))
+done
+
+echo "copying files to the rootdisk"
 touch $MOUNTDIR/etc/{m,fs}tab
 cp {linuxrc,liblinuxlive} $MOUNTDIR # symlink will be copied as original file
 chmod a+x $MOUNTDIR/linuxrc
 
-# find all lib dependences
-for BINARY in cp chmod touch tar gzip gunzip rm bash sh mount umount mv cut \
-              mkdir rmdir ls ln echo cat grep egrep fdisk blockdev \
-	      pivot_root insmod lsmod modprobe depmod swapon eject tail tr \
-	      chroot readlink basename dirname test sleep [ ;
-do
-   for LOCATION in /bin /sbin /usr/bin /usr/sbin ;
-   do
-      if [ -r "$LOCATION/$BINARY" ]; then
-         rcopy "$LOCATION/$BINARY" "$MOUNTDIR"
-
-         list_libs "$LOCATION/$BINARY" | sort | uniq | while read LIB; do
-            if [ ! -a "$MOUNTDIR/$LIB" ]; then
-               rcopy "$LIB" "$MOUNTDIR"
-	    fi
-	 done
-      fi
-   done
-done
-
-# this line can be safely removed when using 2.6 kernel
-cp -R /sbin/*.old $MOUNTDIR/sbin 2>/dev/null
-
-#filesize script by using ls + cut
-echo -ne "#!/bin/bash\necho \`ls -ol \"\$1\"\` | cut -d \" \" -f 4" >$MOUNTDIR/bin/filesize
-chmod 0755 $MOUNTDIR/bin/filesize
+cp binaries/busybox $MOUNTDIR/bin
+cp binaries/unionctl $MOUNTDIR/bin
+ln -s busybox $MOUNTDIR/bin/ash
+ln -s busybox $MOUNTDIR/bin/sh
+ln -s busybox $MOUNTDIR/bin/[
 
 LMK="lib/modules/$KERNEL"
 
 #necessary modules and dependency files
-rcopy /$LMK/kernel/fs/ovlfs $MOUNTDIR
+mkdir -p $MOUNTDIR/$LMK/kernel/fs
+cp kernel-modules/$KERNEL/unionfs.ko.gz $MOUNTDIR/$LMK/kernel/fs
+cp kernel-modules/$KERNEL/squashfs.ko.gz $MOUNTDIR/$LMK/kernel/fs
 
 #copy filesystem modules, if not directly copied into kernel
+rcopy_ex /$LMK/kernel/lib/zlib_inflate $MOUNTDIR 2>/dev/null
+rcopy_ex /$LMK/kernel/drivers/block/loop* $MOUNTDIR 2>/dev/null
+
+rcopy_ex /$LMK/kernel/fs/isofs $MOUNTDIR 2>/dev/null
+rcopy_ex /$LMK/kernel/fs/vfat $MOUNTDIR 2>/dev/null
 rcopy_ex /$LMK/kernel/fs/ntfs $MOUNTDIR 2>/dev/null
 rcopy_ex /$LMK/kernel/fs/ext3 $MOUNTDIR 2>/dev/null
 rcopy_ex /$LMK/kernel/fs/reiserfs $MOUNTDIR 2>/dev/null
 
 #usb modules
-rcopy_ex /$LMK/kernel/drivers/usb/usbcore.* $MOUNTDIR 2>/dev/null
 rcopy_ex /$LMK/kernel/drivers/usb/host $MOUNTDIR 2>/dev/null
 rcopy_ex /$LMK/kernel/drivers/usb/storage $MOUNTDIR 2>/dev/null
 
-#disk (ide, raid, pcmcia, pnp, ide-scsi) modules
-rcopy_ex /$LMK/kernel/drivers/ide $MOUNTDIR
-rcopy_ex /$LMK/kernel/drivers/pcmcia $MOUNTDIR
-rcopy_ex /$LMK/kernel/drivers/pnp $MOUNTDIR
-rcopy_ex /$LMK/kernel/drivers/scsi/ide-scsi.* $MOUNTDIR
+#disk (scsi, ide, raid, pcmcia) modules
+rcopy_ex /$LMK/kernel/drivers/scsi $MOUNTDIR
+#rcopy_ex /$LMK/kernel/drivers/ide $MOUNTDIR
+#rcopy_ex /$LMK/kernel/drivers/pcmcia $MOUNTDIR
 
-chroot $MOUNTDIR depmod -a 2>/dev/null # some dependences may be missing
+echo "generating module dependency files"
+depmod -b $MOUNTDIR
 
-echo "unmounting $MOUNTDIR and gzipping initrd.img..."
+echo "unmounting $MOUNTDIR"
 umount $MOUNTDIR
+
+echo "gzipping initrd.img"
 gzip --best $INITRDIMG
 
-echo "deleting directory $MOUNTDIR..."
+echo "deleting directory $MOUNTDIR"
 rm -Rf $MOUNTDIR
+
+echo "initrd.gz created"
diff --git a/tools/liblinuxlive b/tools/liblinuxlive
--- a/tools/liblinuxlive
+++ b/tools/liblinuxlive
@@ -1,7 +1,12 @@
-#!/bin/bash
-# Functions library :: for Linux Live scripts
-# Author: Tomas Matejicek <http://www.linux-live.org>
+#!/bin/ash
+
+# Functions library :: for Linux Live scripts 5.x.y
+# Author: Tomas M. <http://www.linux-live.org>
 #
+
+# ===========================================================
+# user interface functions
+# ===========================================================
 
 # echolog
 # $1 = text to show and to write to /var/log/messages
@@ -10,6 +15,19 @@ echolog()
 {
    echo "LIVECD:" "$@" >>/var/log/livedbg
    echo "$@"
+}
+
+# debug
+# commands executed when debug boot parameter is present
+#
+debug()
+{
+   echo
+   echo "====="
+   echo ": Debugging started. Here is the root shell for you."
+   echo ": Type your desired command or hit Ctrl+D to continue booting."
+   echo
+   ash
 }
 
 # header
@@ -24,13 +42,27 @@ header()
    echolog " "
 }
 
-# file extension
-# $1 = filename with extension
-# return: whole extension
-#
-file_extension()
+fatal()
 {
-   echo "$1" | egrep -io "\\.[^.]*\$"
+   header "Fatal error occured - $1"
+   echo "Something went wrong and we can't continue booting."
+   echo "You may explore the system by using simple commands like ls, lsmod, mount, etc."
+   echo "Finaly hit Ctrl+Alt+Delete to reboot."
+   echo
+   ash
+}
+
+# ===========================================================
+# text processing functions
+# ===========================================================
+
+# egrep_o is a replacement for "egrep -o". It prints only the last
+# matching text
+# $1 = regular expression
+#
+egrep_o()
+{
+   cat - | egrep "$1" | sed -r "s/.*($1).*/\\1/"
 }
 
 # look into cmdline and echo $1 back if $1 is set
@@ -41,7 +73,7 @@ cmdline_parameter()
 {
    CMDLINE=/proc/cmdline
    if [ ! "$2" = "" ]; then CMDLINE="$2"; fi
-   cat "$CMDLINE" | egrep -io "(^|[[:space:]]+)$1(\$|=|[[:space:]]+)" | egrep -o "[^[:space:]].*[^[:space:]]"
+   cat "$CMDLINE" | egrep_o "(^|[[:space:]]+)$1(\$|=|[[:space:]]+)" | egrep_o "[^[:space:]].*[^[:space:]]"
 }
 
 # look into cmdline and echo value of $1 option
@@ -52,321 +84,255 @@ cmdline_value()
 {
    CMDLINE=/proc/cmdline
    if [ ! "$2" = "" ]; then CMDLINE="$2"; fi
-   cat "$CMDLINE" | egrep -io "(^|[[:space:]]+)$1=([^[:space:]]+)" | egrep -o "[^=]+\$" | tail -n 1
+   cat "$CMDLINE" | egrep_o "(^|[[:space:]]+)$1=([^[:space:]]+)" | egrep_o "=.*" | cut -b 2- | tail -n 1
 }
 
-# create temporary file (empty)
-# $1 = prefix
-#
-tempfile()
-{
-   local NAME=$1
-   if [ "$NAME" = "" ]; then NAME="/tmp/tempfile"; fi
-   while [ -a "$NAME" ]; do
-      NAME=$NAME".X"
-   done
-   touch "$NAME"
-   echolog "$NAME"
-}
+# ===========================================================
+# system functions
+# ===========================================================
 
-# create temp directory in $1 with the preffix $2
-# $1 = prefix to use, it may be a fullpath too
-# (for example tempdir /mnt/cdrom/bin.img /mnt will create /mnt/bin.KJBDRTYH)
-# $2 = subdirectory where tempdir will be created
-#
-tempdir()
-{
-   local TMPDIR
-   if [ "$2" != "" ]; then TMPDIR="$2"; else TMPDIR="/tmp"; fi
-   local MOUNTPOINT=`basename $1`
-
-   MOUNTPOINT="$TMPDIR/$MOUNTPOINT"
-
-   while [ -a "$MOUNTPOINT" ]; do
-      MOUNTPOINT=$MOUNTPOINT".X"
-   done
-
-   mkdir -p "$MOUNTPOINT"
-   if [ $? != 0 ]; then echolog "error creating directory $MOUNTPOINT"; exit 1; fi
-   echolog "$MOUNTPOINT"
-}
-
-# create compressed iso image
-# $1 = input directory tree (for example /bin)
-# $2 = output img file (for example /tmp/bin.iso)
-# $3 = relative root dir string (for example /bin)
-#
-mkciso()
-{
-   RAW=`tempfile`
-   COMPRESSED=`tempfile`
-   if [ "$3" != "" ]; then INPUT="-graft-points $3=$1"; else INPUT="$1"; fi
-
-   mkisofs -R -J -D -o "$RAW" $INPUT 2>/dev/null
-   mkzftree -z 9 -F "$RAW" "$COMPRESSED"
-   if [ ! "$?" = 0 ]; then
-      echolog "mkzftree error: directory $1 is very big? Maybe you are running"
-      echolog "out of disk space, or mkzftree doesn't support large files,"
-      echolog "or mkzftree not found! (get it from cdrtools package)"
-      return 1
-   fi
-   rm -f "$RAW" # it won't be needed anymore
-
-   mkisofs -R -J -D -z -o "$2" -graft-points mountme.iso=$COMPRESSED 2>/dev/null
-   rm -f "$COMPRESSED"
-}
-
-# link all files and directories from $1/* to $2; recursive function
-# $1 = source directory
-# $2 = destination directory
-# $3 = directory to strip, usually /mnt
-#
-make_links()
-{
-   local SOURCEDIR="`dirname \"$1/x\"`"
-   ls -aA1b "$SOURCEDIR" 2>/dev/null | while read FILE;
-   do
-      local DESTFILE="$2/$FILE"
-
-      if [ -L "$SOURCEDIR/$FILE" ]; then
-         rm -rf "$DESTFILE"
-         ln -sf "`readlink \"$SOURCEDIR/$FILE\"`" "$DESTFILE"
-      else
-         if [ -d "$SOURCEDIR/$FILE" ]; then
-            if [ "`ls -aA \"$DESTFILE\" 2>/dev/null`" = "" ]; then
-	       mkdir -p "$DESTFILE"
-	       if [ "`ls -aA \"$SOURCEDIR/$FILE\" 2>/dev/null`" != ""  ]; then
-	          mount -n --rbind "$SOURCEDIR/$FILE" "$DESTFILE"
-	       fi
-            else
-      	       make_writable "$DESTFILE" $3
-               make_links "$SOURCEDIR/$FILE" "$DESTFILE" $3
-	    fi
-	 else
-            rm -rf "$DESTFILE"
-	    ln -sf "${SOURCEDIR:${#3}}/$FILE" "$DESTFILE"
-	 fi
-      fi
-   done
-}
-
-# make a symlink to file or directory writable in LiveCD linked tree; recursive
-# $1 = directory or file I would like to write to
-# $2 = stripped directory which has to be added back now
-#
-make_writable()
-{
-   # not a symlink? exit
-   if [ ! -L "$1" ]; then
-      return 1
-   fi
-
-   local LINKPOINT="$2""`readlink \"$1\"`"
-
-   if [ -d "$1" ]; then            # symlink to a directory?
-      rm -f "$1"                   # remove link
-      mkdir "$1"                   # create real directory instead of it
-      make_links "$LINKPOINT" "$1" # and link the content
-   else                            # symlink to a file?
-      cp -fR "$LINKPOINT" "$1"     # then just copy the original here
-   fi
-}
-
-# try to copy all images to RAM, if commandline parameter copy2ram or toram is present
-# $1 = path to compressed image
-# $2 = destination path
-# return: will echo the final destination of image (the original path if not copied to RAM, or the copy)
-#
-cp2ram()
-{
-   DOCOPY="`cmdline_parameter copy2ram`"
-   if [ "$DOCOPY" = "" ]; then DOCOPY="`cmdline_parameter toram`"; fi
-   IMGNAME="`basename \"$1\"`"
-
-   if [ ! "$DOCOPY" = "" ]; then
-      echolog -n " $IMGNAME" >&2
-      cp "$1" "$2/$IMGNAME"
-
-      if [ $? = 0 ];
-         then echolog "$2/$IMGNAME"; return 0
-         else rm -f "$2/$IMGNAME" # not enough free space?
-      fi
-   fi
-   echolog "$1"
-}
-
-# mount image into unique temporary directory
-# $1 = image to mount
-# $2 = where to create a tmpdir
-# $3 = storage textfile, append mountpoint path there
-# $4 = mount arguments, for example -n will disable writing to /etc/mtab
-#
-mount_img()
-{
-   local MOUNTPOINT=`tempdir $1 $2`
-   mount $4 -o loop,ro $1 $MOUNTPOINT
-   if [ $? != 0 ]; then
-      echolog "!error mounting $1 to $MOUNTPOINT"
-      echolog "Do you have enough free loop devices?"
-      echolog "Or IMG file is corrupted? Can you check md5sum?"
-      return 1
-   fi
-
-   mount $4 -o loop,ro $MOUNTPOINT/mountme.iso $MOUNTPOINT
-   if [ $? != 0 ]; then
-      echolog "!error submounting $1"
-      echolog "Do you have enough free loop devices?"
-      echolog "Do you have transparent decompression for ISO filesystem compiled into kernel?"
-      return 1
-   fi
-   
-   echolog "$MOUNTPOINT" >>$3
-}
-
-# REmount device in $1 directory, in the mode set by $2
-# $1 = directory which is already mounted
-# $2 = mount option for -o remount,("ro", "rw")
-#
-remount()
-{
-   mount -o remount,$2 "`cat /proc/mounts | grep \"$1\" | cut -d \" \" -f 1`" $1 2>/dev/null
-}
-
-# Mount device $1 to $2
-# $1 = /dev device to mount
-# $2 = /mnt mountpoint, directory will be created automatically
-# $3 = mount options, for example "loop" or "remount,ro"
-#
-mount_device()
-{
-  if [ -a "$2" -o ! -b "$1" ]; then return 1; fi # only mount if directory doesn't exist
-  mkdir -p $2
-  if [ "$3" != "" ]; then OPTIONS="-o $3"; fi
-
-  PRINTK=`cat /proc/sys/kernel/printk`
-  echo "0" >/proc/sys/kernel/printk
-
-  mount -t auto $OPTIONS $1 $2 >/dev/null 2>/dev/null
-  err=$?
-
-  if [ "$err" != 0 ]; then rmdir $2; fi
-  echo "$PRINTK" >/proc/sys/kernel/printk
-  return $err
-}
-
-# modprobe module $1, suppress all messages
+# modprobe module $1, including all dependencies, suppress all messages
+# (own function because modprobe in busybox doesn't work with gzipped modules)
 # $1 = module name, eg. ehci-hcd
+# $2 = optional argument
 #
 modprobe_module()
 {
   PRINTK=`cat /proc/sys/kernel/printk`
   echo "0" >/proc/sys/kernel/printk
 
-  modprobe $1 >/dev/null 2>/dev/null
-  err=$?
+  KERNEL="`uname -r`"; LSMOD=/tmp/lsmod
+  MODULEDEPS="`cat /lib/modules/$KERNEL/modules.dep | egrep \"$1\\.ko(\\.gz)?:\"`"
+
+  for MODULE in `echo $MODULEDEPS | cut -d ":" -f 2-` `echo $MODULEDEPS | cut -d ":" -f 1`; do
+     TMPMOD="/tmp/`basename $MODULE .gz`";
+     # if the module is not loaded already
+     if [ "`cat $LSMOD 2>/dev/null | egrep \"^$TMPMOD\\\$\"`" = "" ]; then
+        gunzip -c $MODULE >$TMPMOD
+        if [ "$?" -ne 0 ]; then cp $MODULE $TMPMOD; fi # can't gunzip? copy
+        insmod $TMPMOD $2 >/dev/null 2>/dev/null; err=$?
+        if [ "$err" -eq 0 ]; then echo $TMPMOD >>$LSMOD; fi
+        rm $TMPMOD
+     fi
+  done
 
   echo "$PRINTK" >/proc/sys/kernel/printk
   return $err
 }
 
+# Mount device $1 to $2
+# $1 = /dev device to mount, eg. /dev/hda1
+# $2 = mountpoint, eg. /mnt/hda1
+# $3 = mount options, for example "loop", "ro", or "remount,rw"
+#
+mount_device()
+{
+  mkdir -p $2
+  if [ "$3" != "" ]; then OPTIONS="-o $3"; else OPTIONS=""; fi
+
+  PRINTK=`cat /proc/sys/kernel/printk`
+  echo "0" >/proc/sys/kernel/printk
+
+  mount -t auto $1 $2 $OPTIONS >/dev/null 2>/dev/null
+  err=$?
+
+  if [ "$err" -ne 0 ]; then rmdir $2 2>/dev/null; fi
+  echo "$PRINTK" >/proc/sys/kernel/printk
+  return $err
+}
+
+# ===========================================================
+# live module functions
+# ===========================================================
+
+# Create module
+# call mksquashfs with apropriate arguments
+# $1 = directory which will be compressed to squashfs module
+# $2 = output .mo file
+#
+create_module()
+{
+   mksquashfs $1 $2 >/dev/null
+   chmod oga-x $2 # remove execute attrib
+}
+
+# Mount .mo module to destination directory
+# $1 = path to .mo livecd compressed module
+# $2 = destination folder
+#
+mount_module()
+{
+   mount -t squashfs -o loop,ro $1 $2
+}
+
+# Insert a directory tree $2 to an union specified by $1
+# Top-level read-write branch is specified by it's index 0
+# $1 = union absolute path (starting with /)
+# $2 = path to data directory
+#
+union_insert_dir()
+{
+   unionctl $1 --add --after 0 --mode ro $2
+}
+
+# Insert all .mo modules, in $2 directory and subdirectories, to the union
+# $1 = union absolute path (starting with /)
+# $2 = LiveCD data dir (with directories /base, /modules, etc.)
+# $3 = destination folder, where images will be mounted to
+#
+union_insert_modules()
+{
+   ls -A1d $2/*.mo $2/*/*.mo 2>/dev/null | while read MODULE; do
+      TARGET="$3/`basename $MODULE`"
+      while [ -e $TARGET ]; do TARGET=$TARGET.X; done
+      mkdir -p $TARGET
+      mount_module $1 $TARGET
+      union_insert_dir $1 $TARGET
+   done
+}
+
+# ===========================================================
+# discovery functions
+# ===========================================================
+
 # List all CD-ROMs
 # by using /dev entries (mounted devfs filesystem)
 #
-list_all_cdroms()
+list_cdrom_devices()
 {
-   CDIR=/dev/cdroms
-   if [ ! -d "$CDIR" ]; then return 0; fi
-   ls -aAb1 "$CDIR" | while read FILE ; # list all files in directory
-   do
-      echo "$CDIR/$FILE"
+   for CDDEVICE in `cat /proc/sys/dev/cdrom/info | head -n 3 | tail -n 1 | cut -d ":" -f 2`; do
+      echo "/dev/$CDDEVICE"
    done
 }
 
-# Mount all CDs to $1
-# $1 = mount directory, in which all CDs will be mounted, eg. /mnt/mnt
-# return: echo all mounted devices
-# This won't include empty CD-ROMs!
+# List all partition devices
+# take list of all partitions and output unique disks
 #
-mount_all_cds()
+list_partition_devices()
 {
-   list_all_cdroms | while read DEVICE ;
-   do
-      FILE="`basename $DEVICE`"
-      CDDEV="`readlink -f $DEVICE`"
-      mount_device "$CDDEV" "$1/$FILE" ro
-      echolog "$CDDEV"
+   if [ ! "`cmdline_parameter nohd`" = "" ]; then return; fi
+   cat /proc/partitions | grep -v loop | sed -r "s/^[0-9[:space:]]+/\/dev\//" | grep /dev/
+}
+
+# List all disk devices
+#
+list_disk_devices()
+{
+   list_partition_devices | egrep -v "[0-9]"
+}
+
+# List all block devices
+#
+list_block_devices()
+{
+   list_cdrom_devices
+   list_partition_devices
+}
+
+# Try to mount all disks, partitions and cdroms and Find where the LiveCD is.
+# If LiveCD found in the device, echo dirname of it's directory
+# and leave the device mounted.
+# $1 = directory where devices will be mounted
+#
+find_live_data_dir()
+{
+   list_block_devices | while read DEVICE; do
+      DIR=$1/"`basename $DEVICE`"
+      mount_device $DEVICE $DIR
+      ls -A1d $DIR/livecd.sgn $DIR/*/livecd.sgn 2>/dev/null | \
+        while read FOUND; do dirname "$FOUND"; return 1; done
+      if [ "$?" -eq 0 ]; then umount $DIR 2>/dev/null; rmdir $DIR 2>/dev/null
+      else return 0; fi
    done
 }
 
-# Mount all discs to $1
-# $1 = mount directory, in which all discs will be mounted,  eg. /mnt/mnt
-# return: echo all mounted devices
+# ===========================================================
+# hardware preparation functions
+# ===========================================================
+
+# Create block devices to /dev described by /sys entries
 #
-mount_all_discs()
+create_block_devices()
 {
-   DDIR=/dev/discs
-   if [ ! -d $DDIR ]; then return 0; fi
-   ls -aAb1 $DDIR | while read DISC ; # list all files in directory
-   do
-      ls -aAb1 "$DDIR/$DISC" | grep part | while read PART;
-      do
-         mount_device "$DDIR/$DISC/$PART" "$1/$DISC$PART" ro
-	 echolog "$DDIR/$DISC/$PART"
-      done
+   echolog "creating /dev entries for block devices"
+   ls -A1d /sys/block/*/dev /sys/block/*/*/dev 2>/dev/null | grep -v loop | while read BLOCK; do
+      DEVICE="/dev/`basename \`dirname $BLOCK\``"
+      if [ ! -b $DEVICE ]; then
+         MINORMAJOR="`head -n 1 $BLOCK | tr ':' ' '`"
+         mknod $DEVICE b $MINORMAJOR
+      fi
    done
 }
 
-# Find all swaps and write info for fstab to stdout
+# modprobe kernel modules needed for the LiveCD
 #
-list_swaps()
+modprobe_essential_modules()
 {
-   /sbin/fdisk -l 2>/dev/null | grep -i "Linux swap" | egrep -o "^/dev/[a-z0-9/]+" | while read LINE;
-   do
-      echolog "$LINE swap swap defaults 0 0"
+   echolog "starting loop device support"
+   modprobe_module loop max_loop=256
+   echolog "starting cdrom filesystem support"
+   modprobe_module isofs
+   echolog "starting squashfs support"
+   modprobe_module squashfs
+   echolog "starting unionfs support"
+   modprobe_module unionfs
+   create_block_devices
+}
+
+# modprobe kernel modules needed for USB masstorage devices
+#
+modprobe_usb_modules()
+{
+   echolog "starting USB support, this may take a while"
+   modprobe_module usb-storage
+   modprobe_module ehci-hcd
+   modprobe_module ohci-hcd
+   modprobe_module uhci-hcd
+   create_block_devices
+}
+
+# modprobe kernel modules needed for SCSI disks
+#
+modprobe_scsi_modules()
+{
+   echolog "starting SCSI support, this may take a while"
+   ls /lib/modules/`uname -r`/kernel/drivers/scsi | cut -d . -f 1 | while read MODULE; do
+      if [ "$MODULE" != "sg" -a "$MODULE" != "scsi_debug" ]; then
+         echo "$MODULE..."
+	 modprobe_module $MODULE
+      fi
+   done
+   create_block_devices
+}
+
+# Enable/disable DMA if nodma boot parameter is present
+#
+setup_dma()
+{
+   if [ "`cmdline_parameter nodma`" = "" ]; then USINGDMA=1; else USINGDMA=0; fi
+   for DEVICE in `list_cdrom_devices` `list_disk_devices`; do
+      echo "setting DMA support for $DEVICE =using_dma:$USINGDMA"
+      echo "using_dma:$USINGDMA" >"/proc/ide/`basename $DEVICE`/settings"
    done
 }
 
-# list all library dependencies, using ldd, including all links
-# $1 = binary
+# create correct fstab file in $1/etc/fstab and create apropriate
+# mount directories in $1
+# $1 = root directory (union)
 #
-list_libs()
+activate_fstab()
 {
-   ldd "$1" | egrep -o "[[:space:]]/.*" | cut -b 2- | cut -d " " -f 1 | while read LIB; do
-     echo "$LIB"
-     if [ -L "$LIB" ]; then LIB="`dirname $LIB`/`readlink $LIB`"; echo $LIB; fi
-     list_libs $LIB # even a library could use libraries
+   FSTAB="$1/etc/fstab"
+   echo "tmpfs            /                tmpfs       defaults         0   0" >$FSTAB
+   echo "devpts           /dev/pts         devpts      gid=5,mode=620   0   0" >>$FSTAB
+   echo "proc             /proc            proc        defaults         0   0" >>$FSTAB
+
+   list_block_devices | while read DEVICE; do
+      MOUNTDIR="/mnt/`basename $DEVICE`"
+      echo "$DEVICE $MOUNTDIR auto defaults,noauto 0 0" >>$FSTAB
+      mkdir -p $1/$MOUNTDIR
    done
-}
 
-# rcopy is a recursive cp, which copies also symlink's real source
-# $1 = source (may be a regular file or symlink)
-# $2 = target PARENT
-#
-rcopy()
-{
-   if [ -L "$1" ]; then
-      REALPATH="`readlink -f \"$1\"`"
-      cp --parent -R "$REALPATH" "$2"
-      ln -sf "$REALPATH" "$2/$1"
-   else
-      cp --parent -R "$1" "$2"
-   fi
-   if [ "$?" -ne 0 ]; then
-      echo "---------------------------"
-      echo "Error occured while trying to copy \"$1\" to \"$2\""
-      echo "nevertheless your LiveCD may still work."
-      echo "Possible reason: not enough free space in initrd or source doesn't exist"
-      echo "---------------------------"
-   fi
-}
-
-# copy file/dir only if it exists, else skip with no error
-# $1 = source (may not exist)
-# $2 = target PARENT
-#
-rcopy_ex()
-{
-   if [ -a "$1" ]; then
-      rcopy "$1" "$2"
-   fi
+   fdisk -l 2>/dev/null | grep -i "Linux swap" | egrep "^/dev/" \
+     | cut -f 1 -d " " | sed -r "s/(.+)/\\1 swap swap defaults 0 0/" >>$FSTAB
 }
