Added linux-live 6.0.1.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/initrd/initrd_create b/initrd/initrd_create
--- a/initrd/initrd_create
+++ b/initrd/initrd_create
@@ -3,7 +3,7 @@
 #
 # Author:	  Tomas M. <http://www.linux-live.org>
 
-. ../config || exit 1
+. ../.config || exit 1
 
 # rcopy is a recursive cp, which copies also symlink's real source
 # $1 = source (may be a regular file or symlink)
@@ -11,21 +11,28 @@
 #
 rcopy()
 {
-   if [ -L "$1" ]; then
-      REALPATH="`readlink -f \"$1\"`"
-      cp --parent -R "$REALPATH" "$2"
-      ln -sf "$REALPATH" "$2/$1"
+   CWD=`pwd`
+   cd $ROOT
+   SOURCE="${1:${#ROOT}}"
+   DEST="$2"
+   if [ -L "$SOURCE" ]; then
+      REALPATH="`readlink -f \"$SOURCE\"`"
+      cp --parent -R "$REALPATH" "$DEST"
+      ln -sf "$REALPATH" "$DEST/$SOURCE"
    else
-      cp --parent -R "$1" "$2"
+      cp --parent -R "$SOURCE" "$DEST"
    fi
    if [ "$?" -ne 0 ]; then
+      echo ""
       echo "---------------------------"
-      echo "Error occured while trying to copy \"$1\" to \"$2\""
-      echo "nevertheless your LiveCD may still work."
-      echo "Possible reason: not enough free space in initrd or source doesn't exist"
-      echo "If space is your issue, see 'config' file to increase size of initrd."
+      echo "Error occured while trying to copy \"$SOURCE\""
+      echo "Possible reason: not enough free space in initrd OR source doesn't exist."
+      echo "If space is your issue, see '.config' file to increase size of initrd."
+      echo "If source file doesn't exist, it's a big problem. See DOC/requirements.txt"
       echo "---------------------------"
+      exit 1
    fi
+   cd $CWD
 }
 
 # copy file/dir only if it exists, else skip with no error
@@ -50,11 +57,10 @@ debug()
 
 MOUNTDIR=/tmp/initrd_mountdir_$$
 INITRD_TREE=/tmp/initrd_tree_$$
+INITRDIMG=initrd
 
-if [ ! -d "kernel-modules/$KERNEL" ]; then
-   echo "The directory `pwd`/kernel-modules/$KERNEL doesn't exist."
-   echo "Please create it and copy squashfs.ko and unionfs.ko modules"
-   echo "for your kernel ($KERNEL) to this directory."
+if [ ! -d $ROOT/$LMK ]; then
+   echo "cannot find your kernel modules (*.ko) in $ROOT/$LMK"
    exit 1
 fi
 
@@ -81,22 +87,17 @@ for i in 1 2 3 4 5 6; do
   mknod $INITRD_TREE/dev/tty$i c 4 $i;
 done
 
-loops=255
-while [ $loops -ge 0 ]; do
-   mknod $INITRD_TREE/dev/loop$loops b 7 $loops
-   loops=$(($loops-1))
-done
-
 debug "copying files to the rootdisk"
 touch $INITRD_TREE/etc/{m,fs}tab
-cp {linuxrc,cleanup,liblinuxlive} $INITRD_TREE # symlink will be copied as original file
-chmod a+x $INITRD_TREE/linuxrc
-chmod a+x $INITRD_TREE/cleanup
+cat liblinuxlive | sed -r 's/^LIVECDNAME=.*/LIVECDNAME="'$LIVECDNAME'"/' > $INITRD_TREE/liblinuxlive
+cp {linuxrc,cleanup} $INITRD_TREE
+chmod ago+x $INITRD_TREE/{linuxrc,cleanup}
 
 cp -R rootfs/* $INITRD_TREE
 ln -s busybox $INITRD_TREE/bin/ash
 ln -s busybox $INITRD_TREE/bin/sh
 ln -s busybox $INITRD_TREE/bin/bash
+ln -s busybox $INITRD_TREE/bin/echo
 ln -s busybox $INITRD_TREE/bin/[
 ln -s busybox $INITRD_TREE/bin/mount
 ln -s busybox $INITRD_TREE/bin/umount
@@ -109,50 +110,45 @@ ln -s busybox $INITRD_TREE/bin/head
 ln -s busybox $INITRD_TREE/bin/cat
 ln -s busybox $INITRD_TREE/bin/grep
 ln -s busybox $INITRD_TREE/bin/sleep
+ln -s busybox $INITRD_TREE/bin/sed
+ln -s busybox $INITRD_TREE/bin/mdev
 ln -s bin $INITRD_TREE/sbin
 
-LMK="lib/modules/$KERNEL"
-
-#necessary modules and dependency files
+# necessary modules and dependency files
 mkdir -p $INITRD_TREE/$LMK/kernel/fs
-cp kernel-modules/$KERNEL/unionfs.ko* $INITRD_TREE/$LMK/kernel/fs
-cp kernel-modules/$KERNEL/squashfs.ko* $INITRD_TREE/$LMK/kernel/fs
+rcopy $ROOT/$LMK/kernel/fs/aufs $INITRD_TREE
+rcopy $ROOT/$LMK/kernel/fs/squashfs $INITRD_TREE
 
-#copy filesystem modules, if not directly copied into kernel
-rcopy_ex /$LMK/kernel/lib/zlib_inflate $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/lib/zlib_deflate $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/drivers/block/loop* $INITRD_TREE 2>>$DEBUG
+# copy filesystem modules, if not directly copied into kernel
+rcopy_ex $ROOT/$LMK/kernel/lib/zlib_inflate $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/lib/zlib_deflate $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/drivers/block/loop.* $INITRD_TREE 2>>$DEBUG
 
-rcopy_ex /$LMK/kernel/fs/isofs $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/fs/fat $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/fs/vfat $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/fs/ntfs $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/fs/ext3 $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/fs/reiserfs $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/isofs $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/fat $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/vfat $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/ntfs $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/ext3 $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/reiserfs $INITRD_TREE 2>>$DEBUG
 
 # add language support for filesystems
-rcopy_ex /$LMK/kernel/fs/nls/ $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/nls/nls_cp437.* $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/nls/nls_iso8859-1.* $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/fs/nls/nls_iso8859-2.* $INITRD_TREE 2>>$DEBUG
 
-#usb modules
-rcopy_ex /$LMK/kernel/drivers/usb/storage $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/drivers/usb/host/ehci-hcd* $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/drivers/usb/host/ohci-hcd* $INITRD_TREE 2>>$DEBUG
-rcopy_ex /$LMK/kernel/drivers/usb/host/uhci-hcd* $INITRD_TREE 2>>$DEBUG
+# usb modules
+rcopy_ex $ROOT/$LMK/kernel/drivers/usb/storage $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/drivers/usb/host/ehci-hcd.* $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/drivers/usb/host/ohci-hcd.* $INITRD_TREE 2>>$DEBUG
+rcopy_ex $ROOT/$LMK/kernel/drivers/usb/host/uhci-hcd.* $INITRD_TREE 2>>$DEBUG
 
-#disk (scsi, ide, raid, pcmcia) modules
-#rcopy_ex /$LMK/kernel/drivers/scsi $INITRD_TREE
-#rcopy_ex /$LMK/kernel/drivers/ide $INITRD_TREE
-#rcopy_ex /$LMK/kernel/drivers/pcmcia $INITRD_TREE
-
-if [ "$COMPRESS" = 1 ]; then
-   debug "gzipping kernel modules"
-   find $INITRD_TREE -name "*.ko" | xargs -r gzip --best
-fi
+debug "unpacking all kernel modules for initrd"
+find $INITRD_TREE -name "*.ko.gz" | xargs -r gunzip
 
 debug "generating module dependency files"
 depmod -b $INITRD_TREE $KERNEL
 
-debug "creating empty image file $INITRDIMG"
+debug "creating empty image file for initrd"
 dd if=/dev/zero of=$INITRDIMG bs=1024 count=$RAM0SIZE >>$DEBUG 2>&1
 
 debug "making filesystem"
diff --git a/initrd/linuxrc b/initrd/linuxrc
--- a/initrd/linuxrc
+++ b/initrd/linuxrc
@@ -9,15 +9,19 @@ echolog "mounting /proc and /sys filesystems"
 mount -t proc proc /proc
 mount -t sysfs sysfs /sys
 ln -sf /proc/mounts /etc/mtab # this allows us to use umount -a
+mount -o remount,rw / # for the case we forgot rw boot option
 
-# in some cases, we need USB modules soon
-if [ "`cmdline_parameter probeusb`" != "" ]; then
-   modprobe_usb_modules
-fi
+# use mdev to create /dev/ devices and setup it as a hotplug-handler
+mdev_start_hotplug
 
 # setup DEBUGCMD variable. If debug boot option is present, call debug()
 # function several times during script's execution
 if [ "`cmdline_parameter debug`" ]; then DEBUGCMD="debug"; else DEBUGCMD=""; fi
+
+if [ "$DEBUGCMD" != "" ]; then
+   # debug must support USB keyboard as well
+   modprobe_usb_modules
+fi
 
 $DEBUGCMD
 
@@ -25,7 +29,7 @@ $DEBUGCMD
 RAMSIZE="`cmdline_value ramsize`"
 if [ "$RAMSIZE" = "" ]; then RAMSIZE="60%"; fi
 
-# cdrom support, isofs support, unionfs support, etc
+# cdrom support, isofs support, aufs support, etc
 modprobe_essential_modules
 setup_dma
 echo -e "ext3\next2\nvfat\n*" >/etc/filesystems
@@ -36,83 +40,74 @@ mkdir -p $MEMORY
 $DEBUGCMD
 
 echolog "setup directory for changes"
-CHANGESPATH="`cmdline_value changes`"
-CHANGESPATH="`find_file $MOUNTDIR $CHANGESPATH`"
+CHANGESARG="`cmdline_value changes`"
+CHANGESPATH="`find_file $MOUNTDIR $CHANGESARG`"
 echolog $CHANGESPATH
-mount_device $CHANGESPATH $MEMORY # silently ignored if changespath is empty
 
-# mount tmpfs only in the case when changes= boot parameter was empty
-# or we were not able to mount the storage device
+# if changes= argument is present, but we can't find specified file,
+# load USB modules and try again
+if [ "$CHANGESARG" != "" -a "$CHANGESPATH" = "" ]; then
+   modprobe_usb_modules
+   CHANGESPATH="`find_file $MOUNTDIR $CHANGESARG`"
+fi
+
+mount_device $CHANGESPATH $MEMORY # if empty or failed, mount tmpfs:
 if [ $? -ne 0 ]; then mount -t tmpfs -o "size=$RAMSIZE" tmpfs $MEMORY; fi
 
 # $UNION will be used as a root directory, livecd modules will be added soon
-echolog "setup union directory"
+echolog "setup union directory (using aufs)"
 
 mkdir -p $CHANGES
-if [ 0$? -ne 0 ]; then
-   fatal "it seems you're using a Read-Only filesystem"
+if [ $? -ne 0 ]; then
+   fatal "a Read-Only filesystem is not supported"
 fi
 
 mkdir -p $IMAGES
-mount -t unionfs -o dirs=$CHANGES=rw unionfs $UNION
-if [ $? -ne 0 ]; then fatal "can't setup union"; fi
+mount -t aufs -o br:$CHANGES=rw aufs $UNION
+if [ $? -ne 0 ]; then fatal "can't setup union (aufs)"; fi
 
 $DEBUGCMD
 
-# try to find livecd data directory. If not found, try modprobing
-# USB kernel modules and repeat the find procedure again
-echolog "looking for data modules"
+# try to find livecd data directory.
+echolog "looking for data directory"
 
 DATAFROM="`cmdline_value from`"
 DATAFROM="`find_file $MOUNTDIR $DATAFROM`"
 
-# when from= is used, search for livecd.sgn
+# when from= is used, search for liveCDdata.
 if [ "$DATAFROM" ]; then
-   mount_device $DATAFROM $ISOMOUNT
-   if [ 0$? -eq 0 -a -e "$ISOMOUNT/$LIVECDSGN" ]; then
-      echolog "found in $DATAFROM"
-      DATA=$ISOMOUNT
+   mount_device $DATAFROM $LOOPMOUNT # we must mount again, if loop device
+   if [ $? -eq 0 -a -d "$LOOPMOUNT/$LIVECDNAME" ]; then
+      echolog "found in $LOOPMOUNT"
+      DATA=$LOOPMOUNT/$LIVECDNAME
    fi
 fi
 
 if [ "$DATA" = "" ]; then
-   # from= is not used or it didn't contain livecd.sgn
-   DATA="`find_file $MOUNTDIR $LIVECDSGN`"
-   if [ "$DATA" != "" ]; then
-      DATA="`dirname \"$DATA\"`"
-   fi
+   # from= is not used or it didn't contain liveCDdata
+   DATA="`find_file $MOUNTDIR $LIVECDNAME`"
 fi
 
 if [ "$DATA" = "" ]; then
-   # data still not found, probe for USB devices and wait
-   modprobe_usb_modules;
-   echolog -n "waiting for usb devices .."
-   for i in 1 2 3 4 5 6 7 8; do # max 36 seconds, prolong the delay each time
-      echo -n "."
-      create_block_devices >/dev/null
-      DATA="`find_file $MOUNTDIR $LIVECDSGN`";
-      if [ "$DATA" != "" ]; then
-         DATA="`dirname \"$DATA\"`"
-         break;
-      fi
-      sleep $i;
-   done
+   # Still nothing found? Try USB devices
+   modprobe_usb_modules
+   DATA="`find_file $MOUNTDIR $LIVECDNAME`"
 fi
 
 $DEBUGCMD
 
-if [ "$DATA" = "" ]; then fatal "
-LiveData not found. Searching for $LIVECDSGN file, but the file was not found.
+if [ "$DATA" = "" ]; then fatal \
+"LiveData not found. Searching for $LIVECDNAME directory.
 You are maybe using an unsupported boot device (eg. SCSI or PCMCIA CD-ROM)
-Try to copy all data from CD/USB to your IDE harddisk, for example
-to /mnt/sda1/ in Linux or C:\\ in Windos. Then boot again."
+Try to copy the directory $LIVECDNAME from CD/USB to your IDE/SATA harddisk,
+for example to /mnt/sda1/ in Linux or C:\\ in Windos. Then boot again."
 fi
 
-echolog "LiveData mounted to $DATA"
+echolog "Using $LIVECDNAME data from $DATA"
 
 $DEBUGCMD
 
-# If toram or copy2ram boot parameter is present, copy all .mo modules to RAM.
+# If toram or copy2ram boot parameter is present, copy all fs modules to RAM.
 # (skip modules from /optional/ which are not listed in load= boot option)
 # Finaly modify DATA variable so it will point to correct directory
 if [ "`cmdline_parameter toram`" != "" -o "`cmdline_parameter copy2ram`" != "" ]; then
@@ -131,12 +126,9 @@ if [ "`cmdline_parameter toram`" != "" -o "`cmdline_parameter copy2ram`" != "" ]
    cd_autoeject 0
 fi
 
-mkdir -p $UNION/boot
-mount -o bind $DATA $UNION/boot
-
 $DEBUGCMD
 
-# DATA contains path to the base directory of all .mo images which need
+# DATA contains path to the base directory of all fs modules which need
 # to be mounted and inserted into live filesystem. Do it now.
 echolog "inserting all modules and creating live filesystem"
 union_insert_modules $UNION $DATA $IMAGES
@@ -147,7 +139,7 @@ union_insert_modules $UNION $MEMORY $IMAGES
 
 $DEBUGCMD
 
-echolog "copying rootchanges"
+echolog "copying content of rootcopy directory"
 cp -a $DATA/rootcopy/* $UNION 2>/dev/null # may be empty
 
 $DEBUGCMD
@@ -158,11 +150,15 @@ fstab_update $UNION
 
 # More likely these directories aren't there.
 # Even if they are, this won't hurt.
+mkdir -p $UNION/boot
 mkdir -p $UNION/proc
 mkdir -p $UNION/sys
 mkdir -p $UNION/dev
 mkdir -p $UNION/tmp
 chmod 0777 $UNION/tmp
+
+# boot will contain whatever was in ./boot directory in the bootable media
+mount -o rbind `dirname $DATA`/boot $UNION/boot
 
 $DEBUGCMD
 
@@ -172,19 +168,30 @@ $DEBUGCMD
 echolog "changing root directory..."
 
 cd $UNION
+
 umount /sys # we won't need it anymore
 mkdir -p $INITRAMDISK
-if [ ! -e dev/console ]; then mknod dev/console c 5 1; fi
 
-if [ -x $UNION/usr/sbin/chroot ];
-  then CHROOT=/usr/sbin/chroot
-  else CHROOT=/usr/bin/chroot
-fi
+# Copy all dev files (found by mdev) to unioned dev directory
+# so at least disk devices exist (your Linux may need them)
+if [ ! -e /dev/console ]; then mknod /dev/console c 5 1; fi
+cp -fdR /dev .
 
+# find chroot and init
+if [ -x usr/bin/chroot ]; then  CHROOT=/usr/bin/chroot; fi
+if [ -x usr/sbin/chroot ]; then CHROOT=/usr/sbin/chroot; fi
+if [ "$CHROOT" = "" ]; then fatal "Can't find executable chroot command"; fi
+
+if [ -x bin/init ]; then INIT=bin/init; fi
+if [ -x sbin/init ]; then INIT=sbin/init; fi
+if [ "$INIT" = "" ]; then fatal "Can't find executable init command"; fi
+
+# time to end Linux Live scripts and start the distribution itself
 header "linux live end, starting the Linux distribution"
-pivot_root . $INITRAMDISK
-exec $CHROOT . sbin/init <dev/console >dev/console 2>&1
 
-header "ERROR!"
-echolog "You are not supposed to be here, something went wrong!"
-echolog "Even Ctrl+Alt+Del won't help you in kernel panic."
+mount -o remount,ro .
+pivot_root . $INITRAMDISK
+exec $CHROOT . $INIT <dev/console >dev/console 2>&1
+
+header "!!ERROR!!"
+fatal "You are not supposed to be here, something went wrong!"
diff --git a/tools/liblinuxlive b/tools/liblinuxlive
--- a/tools/liblinuxlive
+++ b/tools/liblinuxlive
@@ -1,6 +1,6 @@
 #!/bin/ash
 
-# Functions library :: for Linux Live scripts 5.x.y
+# Functions library :: for Linux Live scripts 6.x.y
 # Author: Tomas M. <http://www.linux-live.org>
 #
 
@@ -20,8 +20,10 @@ CHANGES=$MEMORY/changes
 COPY2RAM=$MEMORY/copy2ram
 IMAGES=$MEMORY/images
 INITRAMDISK=$MOUNTDIR/live
-ISOMOUNT=$MOUNTDIR/iso
-LIVECDSGN=livecd.sgn
+LOOPMOUNT=$MOUNTDIR/tmp
+
+# this will be replaced by build script, so don't change the following line!
+LIVECDNAME="linux"
 
 # ===========================================================
 # user interface functions
@@ -42,9 +44,16 @@ echolog()
 {
    if [ "$1" != "" ]; then
       echogreen "* "
-      echo "LIVECD:" "$@" >>/var/log/livedbg
+      log "LIVECD:" "$@" 
       echo "$@"
    fi
+}
+
+# log
+# store given text in /var/log/livedbg
+log()
+{
+   echo "$@" >>/var/log/livedbg
 }
 
 # debug
@@ -76,7 +85,7 @@ fatal()
    echolog "Something went wrong and we can't continue. This should never happen."
    echolog "Please reboot your computer with Ctrl+Alt+Delete ..."
    echolog
-   umount -a -r
+   umount -a -r 2>/dev/null
    mount -t proc proc /proc
    mount -t sysfs sysfs /sys
    ash < /dev/console
@@ -105,13 +114,14 @@ egrep_o()
 }
 
 # look into cmdline and echo $1 back if $1 is set
-# $1 = value name, case sensitive, for example livecd_subdir
+# $1 = value name, case sensitive, for example changes
 # $2 = file to use instead /proc/cmdline, optional
 #
 cmdline_parameter()
 {
    CMDLINE=/proc/cmdline
    if [ "$2" != "" ]; then CMDLINE="$2"; fi
+   log "searching for boot param: $1"
    cat "$CMDLINE" | egrep_o "((^|[[:space:]]+)$1(\$|=|[[:space:]]+))" | egrep_o "($1)"
 }
 
@@ -123,6 +133,7 @@ cmdline_value()
 {
    CMDLINE=/proc/cmdline
    if [ "$2" != "" ]; then CMDLINE="$2"; fi
+   log "searching for bootparam value: $1"
    cat "$CMDLINE" | egrep_o "((^|[[:space:]]+)$1=([^[:space:]]+))" | egrep_o "(=.*)" | cut -b 2- | tail -n 1
 }
 
@@ -138,27 +149,7 @@ cmdline_value()
 modprobe_module()
 {
   if [ "$1" = "" ]; then return 1; fi
-  PRINTK=`cat /proc/sys/kernel/printk`
-  echo "0" >/proc/sys/kernel/printk
-
-  KERNEL="`uname -r`"; LSMOD=/tmp/_lsmod
-  MODULEDEPS="`cat /lib/modules/$KERNEL/modules.dep | egrep \"$1\\.ko(\\.gz)?:\"`"
-
-  for MODULE in `echo $MODULEDEPS | cut -d ":" -f 2-` `echo $MODULEDEPS | cut -d ":" -f 1`; do
-     TMPMOD="/tmp/`basename $MODULE .gz`";
-     # if the module is not loaded already
-     if [ "`cat $LSMOD 2>/dev/null | egrep \"^$TMPMOD\\\$\"`" = "" ]; then
-        gunzip -c $MODULE 2>/dev/null >$TMPMOD
-        if [ 0$? -ne 0 ]; then cp $MODULE $TMPMOD; fi # can't gunzip? copy
-        insmod $TMPMOD $2 >/dev/null 2>/dev/null; err=$?
-        if [ 0$err -eq 0 ]; then echo $TMPMOD >>$LSMOD; fi # module log
-        rm $TMPMOD
-     fi
-  done
-
-  echo "$PRINTK" >/proc/sys/kernel/printk
-  if [ 0$err -ne 0 ]; then echolog "error inserting module $1 ($err) for your kernel `uname -r`"; fi
-  return $err
+  modprobe $1 $2 2>/dev/null
 }
 
 # Mount device $1 to $2
@@ -196,7 +187,7 @@ fumount()
 {
    while [ "$1" ]; do
       umount "$1" >/dev/null 2>&1
-      if [ 0$? -ne 0 ]; then
+      if [ $? -ne 0 ]; then
          umount -l "$1" >/dev/null 2>&1
       fi
       shift
@@ -210,14 +201,14 @@ fumount()
 # Create module
 # call mksquashfs with apropriate arguments
 # $1 = directory which will be compressed to squashfs module
-# $2 = output .mo file
+# $2 = output filesystem module file
 # $3 = optional -keep-as-directory argument
 #
 create_module()
 {
    mksquashfs "$1" "$2" $3 >/dev/null
-   if [ 0$? -ne 0 ]; then return 1; fi
-   chmod oga-x "$2" # remove execute attrib
+   if [ $? -ne 0 ]; then return 1; fi
+   chmod oga-wx "$2" # remove execute attrib
 }
 
 # Mountpoint exits with 0 if $1 is mountpoint, else exits with 1
@@ -228,8 +219,8 @@ mountpoint()
    cat /proc/mounts | cut -d " " -f 2 | egrep "^$1\$" >/dev/null 2>&1
 }
 
-# Mount .mo module to destination directory
-# $1 = path to .mo livecd compressed module
+# Mount filesystem module to destination directory
+# $1 = path to the compressed module
 # $2 = destination folder
 #
 mount_module()
@@ -261,7 +252,7 @@ list_modules()
 {
    LOAD="`cmdline_value load | sed -r 's/\*/.\*/g' | sed -r 's/,|;/|/g'`"
    NOLOAD="`cmdline_value noload | sed -r 's/\*/.\*/g' | sed -r 's/,|;/|/g'`"
-   find $1/base $1/modules $1/optional -name "*.mo" 2>/dev/null | sort | while read LINE; do
+   find $1/base $1/modules $1/optional -name "*.lzm" 2>/dev/null | sort | while read LINE; do
       MODNAME="`echo $LINE | cut -b ${#1}- | cut -b 2-`"
       if [ "`echo $LINE | grep /optional/`" ]; then
          if [ ! "$LOAD" -o ! "`echo $MODNAME | egrep -i \"$LOAD\"`" ]; then continue; fi
@@ -271,9 +262,9 @@ list_modules()
    done
 }
 
-# Insert one single .mo module to the union
+# Insert one single filesystem module to the union
 # $1 = union absolute path
-# $2 = module.mo full path
+# $2 = module full path
 # $3 = destination folder, where images will be mounted to
 # $4 = preffix length strip (number of characters)
 #
@@ -283,15 +274,15 @@ union_insert_module()
    if mountpoint $TARGET >/dev/null 2>&1; then return; fi # skip mounted modules
    mkdir -p $TARGET
    mount_module $2 $TARGET
-   if [ 0$? -ne 0 ]; then echo "Cannot read module data. corrupted download?" >&2; return 1; fi
+   if [ $? -ne 0 ]; then echo "Cannot read module data. corrupted download?" >&2; return 1; fi
    union_insert_dir $1 $TARGET
-   if [ 0$? -ne 0 ]; then echo "can't insert module to union" >&2; return 2; fi
+   if [ $? -ne 0 ]; then echo "can't insert module to union" >&2; return 2; fi
    echo "$2" | cut -b $4- | cut -b 2-
    echolog "$2" >/dev/null
    return 0
 }
 
-# Insert all .mo modules, in $2 directory and subdirectories, to the union
+# Insert all filesystem modules, in $2 directory and subdirectories, to the union
 # $1 = union absolute path (starting with /)
 # $2 = LiveCD data dir (with directories /base, /modules, etc.)
 # $3 = destination folder, where images will be mounted to
@@ -377,8 +368,11 @@ list_block_devices()
 find_filepath()
 {
    DIR="$1/`basename $2`"
-   mount_device $2 $DIR
-   if [ 0$? -ne 0 ]; then rmdir $DIR 2>/dev/null; return 1; fi
+   mountpoint $DIR >/dev/null 2>&1
+   if [ $? -ne 0 ]; then
+      mount_device $2 $DIR; 
+      if [ $? -ne 0 ]; then rmdir $DIR 2>/dev/null; return 1; fi
+   fi
    FOUND="`ls -A1d $DIR/$3 2>/dev/null | head -n 1`"
    if [ "$FOUND" = "" ]; then umount $DIR 2>/dev/null; rmdir $DIR 2>/dev/null; return 1
    else echo "$FOUND" | tr -s '/'; return 0; fi
@@ -393,9 +387,9 @@ find_file()
 {
    # if parameter is just a device, echo it and exit
    if [ -b "$2" -o -c "$2" -o "$2" = "" ]; then echo "$2"; return; fi
-   # if path doesn't start with /dev/, find the path exactly on all devices
 
-   # split DEV/PATH parts
+   # If path doesn't start with /dev/, find the path exactly on all devices.
+   # First, split DEV/PATH parts
    DEVPART="`echo \"$2\" | egrep_o \"(^/dev/[^/]+)\"`"
 
    if [ "$DEVPART" = "" ]; then
@@ -403,7 +397,7 @@ find_file()
       PATHPART="$2";
       list_block_devices | while read DEVICE; do
          find_filepath $1 $DEVICE $PATHPART
-         if [ 0$? -eq 0 ]; then return 0; fi
+         if [ $? -eq 0 ]; then return 0; fi
       done
    else
       # try to find PATHPART only on the given device
@@ -418,30 +412,28 @@ find_file()
 
 # Create block devices to /dev described by /sys entries
 #
-create_block_devices()
+mdev_start_hotplug()
 {
    echolog "creating /dev entries for block devices"
-   ls -A1d /sys/block/*/dev /sys/block/*/*/dev 2>/dev/null | grep -v loop | while read BLOCK; do
-      DEVICE="/dev/`basename \`dirname $BLOCK\``"
-      if [ ! -b $DEVICE ]; then
-         MINORMAJOR="`head -n 1 $BLOCK | tr ':' ' '`"
-         mknod $DEVICE b $MINORMAJOR
-      fi
-   done
+   mdev -s
+   echo /bin/mdev > /proc/sys/kernel/hotplug
 }
 
 # modprobe kernel modules needed for the LiveCD
 #
 modprobe_essential_modules()
 {
+   PRINTK=`cat /proc/sys/kernel/printk`
+   echo "0" >/proc/sys/kernel/printk
+
    echolog "starting loop device support"
    modprobe_module loop max_loop=255
    echolog "starting cdrom filesystem support"
    modprobe_module isofs
    echolog "starting squashfs support"
    modprobe_module squashfs
-   echolog "starting unionfs support"
-   modprobe_module unionfs
+   echolog "starting aufs support"
+   modprobe_module aufs
    echolog "starting vfat support"
    modprobe_module nls_cp437
    modprobe_module nls_iso8859-1
@@ -449,23 +441,39 @@ modprobe_essential_modules()
    modprobe_module vfat
    echolog "starting ntfs support"
    modprobe_module ntfs
-   create_block_devices
+
+   echo "$PRINTK" >/proc/sys/kernel/printk
 }
 
 # modprobe kernel modules needed for USB masstorage devices
 #
 modprobe_usb_modules()
 {
-   SLEEP="`cmdline_value probeusb | sed -r 's/[^0-9]*([0-9]+).*/\1/'`"
-   if [ "$SLEEP" = "" ]; then SLEEP=5; fi
+   PRINTK=`cat /proc/sys/kernel/printk`
+   echo "0" >/proc/sys/kernel/printk
 
-   echolog "starting USB support"
-   modprobe_module ehci-hcd
-   modprobe_module ohci-hcd
-   modprobe_module uhci-hcd
+   LSPCI="`lspci -v | grep -i prog-if`"
+   if [ "`echo $LSPCI | egrep -i [eou]hci`" = "" ]; then
+      return
+   fi
+
+   echolog "starting USB support..."
+   if [ "`echo $LSPCI | grep -i ehci`" != "" ]; then
+      modprobe_module ehci-hcd
+   fi
+   if [ "`echo $LSPCI | grep -i ohci`" != "" ]; then
+      modprobe_module ohci-hcd
+   fi
+   if [ "`echo $LSPCI | grep -i uhci`" != "" ]; then
+      modprobe_module uhci-hcd
+   fi
    modprobe_module usb-storage
+
+   SLEEP="`cmdline_value waitusb | sed -r 's/[^0-9]*([0-9]+).*/\1/'`"
+   if [ "$SLEEP" = "" ]; then SLEEP=10; fi
+
    sleep $SLEEP
-   create_block_devices
+   echo "$PRINTK" >/proc/sys/kernel/printk
 }
 
 # enable/disable CD autoejecting when unmounted
@@ -537,6 +545,7 @@ fstab_update()
       # add special options for NTFS
       if [ "$FS" = "ntfs" ]; then
          OPT=",ro"
+#	 FS="ntfs-3g"
          if [ "$IOCHARSET" != "" ]; then OPT="$OPT,nls=$IOCHARSET"; fi
       fi
 
diff --git a/tools/uselivemod b/tools/uselivemod
--- a/tools/uselivemod
+++ b/tools/uselivemod
@@ -1,48 +1,52 @@
 #!/bin/bash
 # Use module while running LiveCD
 # include it into live directory structure on the fly
-# Or install it if no union is found at /
 #
 # Author: Tomas M. <http://www.linux-live.org>
 
 MODULE="$1"
 
-if [ "$MODULE" = "" ]; then
+if [ "$MODULE" = "" -o ! -e "$MODULE" ]; then
    echo
    echo "Use module on the fly while running Live CD"
-   echo "Usage: $0 module.mo"
-   exit
+   echo "Usage: $0 module.lzm"
+   exit 1
+fi
+
+if [ "`echo $MODULE | fgrep -i .lzm`" = "" ]; then
+   echo
+   echo "`basename $MODULE`: Module must end with .lzm"
+   echo "If you have .mo extension, convert it by using mo2lzm"
+   exit 2
 fi
 
 PATH=.:$(dirname $0):/usr/lib:$PATH
-. liblinuxlive || exit 1
+. liblinuxlive || exit 3
 
 allow_only_root
 IMAGES=/mnt/live/memory/images
 MODULES=/mnt/live/memory/modules
 
 # are we even using union?
-unionctl --query / >/dev/null 2>&1
+unionctl / --list 2>/dev/null >/dev/null
 if [ $? -ne 0 ]; then
-   echo "Installing (unpacking) module $MODULE"
-   mo2dir $MODULE /
-   /sbin/ldconfig
-   exit 0
+   echo "not in the live mode, can't continue. Try lzm2dir"
+   exit 4
 fi
 
 mkdir -p "$MODULES"
 
-# test whether the module file is stored in union
-# if yes, then we must move it somewhere else (to RAM)
-unionctl --query "$MODULE" >/dev/null 2>&1
-if [ $? -eq 0 ]; then
+# Test whether the module file is stored in union
+# if yes, then we must move it somewhere else (to RAM) else it can't be added
+unionctl / --whereis "$MODULE"
+if [ $? -ne 0 ]; then
    echo "module file is stored inside the union, moving to $MODULES first..."
    TARGET="$MODULES/`basename \"$MODULE\"`"
    mv "$MODULE" "$TARGET"
    if [ $? -ne 0 ]; then
       echo "error copying module to memory, not enough free RAM? try df" >&2
       rm "$TARGET"
-      return 2
+      exit 6
    fi
    MODULE="$TARGET"
 fi
@@ -51,11 +55,11 @@ MOD="`union_insert_module / \"$MODULE\" $IMAGES`"
 if [ $? -ne 0 ]; then echo "error inserting module to live filesystem" >&2; exit 3; fi
 
 # all executables in /etc/rc.d/ from this module will be started
-# with two arguments: "start" "mo". This happens only by this script (uselivemod),
+# with two arguments: "start" "lzm". This happens only by this script (uselivemod),
 # not in the case when module is loaded during OS startup.
 find $IMAGES/$MOD/etc/rc.d -type f 2>/dev/null | while read SCRIPT; do
    if [ "$SCRIPT" != "" -a -x "$SCRIPT" -a ! -d "$SCRIPT" ]; then
-      ${SCRIPT##$IMAGES/$MOD} start mo
+      ${SCRIPT##$IMAGES/$MOD} start lzm
    fi
 done
 
