Added linux-live 5.4.0.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/initrd/initrd_create b/initrd/initrd_create
--- a/initrd/initrd_create
+++ b/initrd/initrd_create
@@ -23,6 +23,7 @@ rcopy()
       echo "Error occured while trying to copy \"$1\" to \"$2\""
       echo "nevertheless your LiveCD may still work."
       echo "Possible reason: not enough free space in initrd or source doesn't exist"
+      echo "If space is your issue, see 'config' file to increase size of initrd."
       echo "---------------------------"
    fi
 }
@@ -51,8 +52,15 @@ MOUNTDIR=/tmp/initrd_mountdir_$$
 INITRD_TREE=/tmp/initrd_tree_$$
 
 if [ ! -d "kernel-modules/$KERNEL" ]; then
-   echo "The directory ./kernel-modules/$KERNEL doesn't exist. Please create it and copy"
-   echo "squashFS and unionFS modules for your kernel version to it."
+   echo "The directory `pwd`/kernel-modules/$KERNEL doesn't exist."
+   echo "Please create it and copy squashfs.ko and unionfs.ko modules"
+   echo "for your kernel (`uname -r`) to this directory."
+   exit 1
+fi
+
+if [ "`ls -1 rootfs/lib`" = "" ]; then
+   echo "cannot find essential libc libraries."
+   echo "please add ld-linux and libc.so to `pwd`./rootfs/lib"
    exit 1
 fi
 
@@ -84,12 +92,12 @@ touch $INITRD_TREE/etc/{m,fs}tab
 cp {linuxrc,liblinuxlive} $INITRD_TREE # symlink will be copied as original file
 chmod a+x $INITRD_TREE/linuxrc
 
-cp static-binaries/modprobe $INITRD_TREE/sbin
-cp static-binaries/busybox $INITRD_TREE/bin
-cp static-binaries/{unionctl,uniondbg} $INITRD_TREE/bin # symlink will be copied as original file
+cp -R rootfs/* $INITRD_TREE
 ln -s busybox $INITRD_TREE/bin/ash
 ln -s busybox $INITRD_TREE/bin/sh
+ln -s busybox $INITRD_TREE/bin/bash
 ln -s busybox $INITRD_TREE/bin/[
+ln -s bin $INITRD_TREE/sbin
 
 LMK="lib/modules/$KERNEL"
 
@@ -164,6 +172,6 @@ debug "deleting directory $MOUNTDIR"
 rmdir $MOUNTDIR
 
 debug "deleting directory $INITRD_TREE"
-rm -Rf $INITRD_TREE
+#rm -Rf $INITRD_TREE
 
 debug "$INITRDIMG.gz created"
diff --git a/tools/liblinuxlive b/tools/liblinuxlive
--- a/tools/liblinuxlive
+++ b/tools/liblinuxlive
@@ -10,7 +10,7 @@
 
 # linux live flag to fstab, if fstab line doesn't contain it,
 # never remove it from fstab automatically (user added it)
-FSTABLLFLAG="# allow autochange"
+FSTABLLFLAG="# Auto-Update"
 
 # ===========================================================
 # user interface functions
@@ -48,15 +48,12 @@ header()
 
 fatal()
 {
+   echolog
    header "Fatal error occured - $1"
    echolog "Something went wrong and we can't continue. This should never happen."
-   echolog "Please explore the system by using simple commands like mount or dmesg"
-   echolog "and if you found how to fix the bug, let me know at bugs@linux-live.org."
-   echolog "This way we can make linux live scripts even better. Thank you."
-   echolog "If you hit Ctrl+D now, the booting will continue. But use at your own risk."
-   echolog "To be safe, hit Ctrl+Alt+Delete to reboot."
+   echolog "Please reboot your computer with Ctrl+Alt+Delete ... sleeping 20 sec."
    echolog
-   ash
+   sleep 20
 }
 
 allow_only_root()
@@ -133,7 +130,7 @@ modprobe_module()
   done
 
   echo "$PRINTK" >/proc/sys/kernel/printk
-  if [ "$err" -ne 0 ]; then echolog "error inserting module $1 ($err)"; fi
+  if [ "$err" -ne 0 ]; then echolog "error inserting module $1 ($err) for your kernel `uname -r`"; fi
   return $err
 }
 
@@ -141,16 +138,18 @@ modprobe_module()
 # $1 = /dev device to mount, eg. /dev/hda1
 # $2 = mountpoint, eg. /mnt/hda1
 # $3 = mount options, for example "loop", "ro", or "remount,rw"
+# $4 = filesystem type
 #
 mount_device()
 {
   mkdir -p $2
   if [ "$3" != "" ]; then OPTIONS="-o $3"; else OPTIONS=""; fi
+  if [ "$4" != "" ]; then FILESYSTEM="-t $4"; else FILESYSTEM=""; fi
 
   PRINTK=`cat /proc/sys/kernel/printk`
   echo "0" >/proc/sys/kernel/printk
 
-  mount -t auto $1 $2 $OPTIONS >/dev/null 2>/dev/null
+  mount $FILESYSTEM $1 $2 $OPTIONS >/dev/null 2>/dev/null
   err=$?
 
   if [ "$err" -ne 0 ]; then rmdir $2 2>/dev/null; fi
@@ -210,7 +209,7 @@ list_modules()
 }
 
 # Insert one single .mo module to the union
-# $1 = union absolute path (starting with /)
+# $1 = union absolute path
 # $2 = module.mo full path
 # $3 = destination folder, where images will be mounted to
 #
@@ -220,9 +219,9 @@ union_insert_module()
    while [ -e $TARGET ]; do TARGET=$TARGET.X; done
    mkdir -p $TARGET
    mount_module $2 $TARGET
-   if [ $? -ne 0 ]; then echo "can't read module data. corrupted download?" >&2; return 1; fi
+   if [ $? -ne 0 ]; then echo "Cannot read module data. corrupted download?" >&2; return 1; fi
    union_insert_dir $1 $TARGET
-   if [ $? -ne 0 ]; then echo "can't insert module to union" >&2; return 1; fi
+   if [ $? -ne 0 ]; then echo "can't insert module to union" >&2; return 2; fi
    basename $TARGET
 }
 
@@ -246,9 +245,11 @@ union_insert_modules()
 #
 copy_to_ram()
 {
-   cp -R "$1/boot" "$2"
+   cp -R "$1/boot" "$2" # kernel is not required but it's nice2have
    list_modules "$1" | while read MODULE; do
-      cp "$MODULE" "$2"
+      TARGET="$2/`basename \`dirname $MODULE\``"
+      mkdir -p "$TARGET"
+      cp "$MODULE" "$TARGET"
       if [ "$?" -ne 0 ]; then fatal "can't copy to RAM, not enough memory?"; fi
    done
 }
@@ -272,19 +273,18 @@ copy_rootchanges()
 list_cdrom_devices()
 {
    if [ "`cmdline_parameter nocd`" != "" ]; then return 1; fi
-   for CDDEVICE in `cat /proc/sys/dev/cdrom/info | head -n 3 | tail -n 1 | cut -d ":" -f 2`; do
+   for CDDEVICE in `cat /proc/sys/dev/cdrom/info 2>/dev/null | head -n 3 | tail -n 1 | cut -d ":" -f 2`; do
       echo "/dev/$CDDEVICE"
    done
 }
 
-# List all partition devices
-# take list of all partitions and output unique disks.
+# List all devices with filesystems
 # Return empty result when nohd parameter was given.
 #
 list_partition_devices()
 {
    if [ "`cmdline_parameter nohd`" != "" ]; then return 1; fi
-   cat /proc/partitions | grep -v loop | sed -r "s/^[0-9[:space:]]+/\/dev\//" | grep /dev/
+   blkid | grep -v swap | cut -d : -f 1 | grep -v loop
 }
 
 # List all disk devices
@@ -292,6 +292,14 @@ list_partition_devices()
 list_disk_devices()
 {
    list_partition_devices | egrep -v "[0-9]"
+}
+
+# List all partitions marked as Linux Swap
+#
+list_swap_devices()
+{
+   if [ "`cmdline_parameter nohd`" != "" ]; then return 1; fi
+   blkid -t TYPE="swap" | cut -d : -f 1
 }
 
 # List all block devices
@@ -368,6 +376,7 @@ modprobe_usb_modules()
    modprobe_module ohci-hcd
    modprobe_module uhci-hcd
    modprobe_module usb-storage
+   sleep 5
    create_block_devices
 }
 
@@ -391,48 +400,61 @@ setup_dma()
    fi
 }
 
+# update given line in fstab, add new values only if the device is not found
+# $1 = fstab file to parse
+# $2 = device name
+# $3 = mountpoint
+# $4 = filesystem
+# $5 = mount options
+#
+fstab_update_line()
+{
+   if [ "`cat \"$1\" | egrep \"^[[:space:]]*[^[:space:]]+[[:space:]]+$3\"`" = "" ]; then
+      echo "$2" "$3" "$4" "$5" 0 0 "$FSTABLLFLAG" >>$1
+   fi
+}
+
 # create correct fstab file in $1/etc/fstab and create apropriate
-# mount directories in $1
+# mount directories in $1/mnt
 # $1 = root directory (union)
 #
-activate_fstab()
+fstab_update()
 {
-   mkdir -p $1/etc
+   mkdir -p $1/etc $1/mnt
+
    FSTAB="$1/etc/fstab"
-   echo "tmpfs            /                tmpfs       defaults         0   0" >$FSTAB
-   echo "devpts           /dev/pts         devpts      gid=5,mode=620   0   0" >>$FSTAB
-   echo "proc             /proc            proc        defaults         0   0" >>$FSTAB
+   cat $FSTAB 2>/dev/null | grep -v "$FSTABLLFLAG" >$FSTAB~
+
+   fstab_update_line $FSTAB~ tmpfs / tmpfs defaults
+   fstab_update_line $FSTAB~ devpts /dev/pts devpts gid=5,mode=620
+   fstab_update_line $FSTAB~ proc /proc proc defaults
 
    list_cdrom_devices | while read DEVICE; do
       MOUNTDIR="/mnt/`basename $DEVICE`_cdrom"
       mkdir -p $1/$MOUNTDIR
-      echo "$DEVICE $MOUNTDIR iso9660 noauto,users,exec 0 0 $FSTABLLFLAG" >>$FSTAB
+      fstab_update_line $FSTAB~ $DEVICE $MOUNTDIR iso9660 noauto,users,exec
    done
 
    list_partition_devices | while read DEVICE; do
       unset REMOVABLE; DEV="`basename $DEVICE`"; DEV0="`echo $DEV | cut -b 1-3`"
-      if [ "0`cat /sys/block/$DEV0/removable`" -ne 0 ]; then
+      if [ "0`cat /sys/block/$DEV0/removable 2>/dev/null`" -ne 0 ]; then
          REMOVABLE="_removable"
       fi
 
-      # skip this device if mountpoint exists
       MOUNTDIR="/mnt/$DEV$REMOVABLE"
-      if [ -d "$1/$MOUNTDIR" ]; then continue; fi
-
-      # try to mount the device and unmount it. If OK, we can add it to fstab
-      mount_device "$DEVICE" "$1/$MOUNTDIR"
-      FS="`cat /proc/mounts | grep $DEVICE | grep $MOUNTDIR | cut -d \" \" -f 3 | head -n 1`"
-      umount "$1/$MOUNTDIR" 2>/dev/null
-      if [ $? -eq 0 ]; then
-         echo "$DEVICE $MOUNTDIR $FS auto,users,suid,dev,exec 0 0 $FSTABLLFLAG" >>$FSTAB
-      else # remove empty directory
-         rmdir "$1/$MOUNTDIR" 2>/dev/null
+      FS="`blkid -s TYPE $DEVICE | cut -d = -f 2 | tr -d '\"'`"
+      if [ "$FS" != "" ]; then
+         fstab_update_line $FSTAB~ $DEVICE $MOUNTDIR $FS auto,users,suid,dev,exec
+         mkdir -p "$1/$MOUNTDIR"
       fi
    done
 
-   fdisk -l 2>/dev/null | grep -i "Linux swap" | egrep "^/dev/" \
-     | cut -f 1 -d " " | sed -r "s/(.+)/\\1 swap swap defaults 0 0 $FSTABLLFLAG/" >>$FSTAB
+   list_swap_devices | while read DEVICE; do
+      fstab_update_line $FSTAB~ $DEVICE swap swap defaults
+   done
 
-   echo "/dev/fd0 /mnt/floppy auto noauto,users,suid,dev,exec 0 0" >>$FSTAB
+   fstab_update_line $FSTAB~ /dev/fd0 /mnt/floppy vfat,msdos noauto,users,suid,dev,exec
    mkdir -p $1/mnt/floppy
+   
+   mv -f $FSTAB~ $FSTAB
 }
diff --git a/tools/uselivemod b/tools/uselivemod
--- a/tools/uselivemod
+++ b/tools/uselivemod
@@ -1,10 +1,13 @@
 #!/bin/bash
 # Use module while running LiveCD
 # include it into live directory structure on the fly
-# Author: Tomas M. <http://www.linux-live.org>
+# Or install it if no union is found at /
 #
+# Author: Tomas M. <http://www.linux-live.org>
 
-if [ "$1" = "" ]; then
+MODULE="$1"
+
+if [ "$MODULE" = "" ]; then
    echo
    echo "Use module on the fly while running Live CD"
    echo "Usage: $0 module.mo"
@@ -19,10 +22,36 @@ fi
 
 allow_only_root
 IMAGES=/mnt/live/memory/images
+MODULES=/mnt/live/memory/modules
 
-# unionfs must be compiled with -DSETUP_BROKEN_LOSETUP=1 else this won't work!
-MOD="`union_insert_module / \"$1\" $IMAGES`"
-if [ $? -ne 0 ]; then echo "error inserting module to live filesystem" >&2; exit 1; fi
+# are we even using union?
+unionctl --query / >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+   echo "Installing (unpacking) module $MODULE"
+   mo2dir $MODULE /
+   /sbin/ldconfig
+   exit 0
+fi
+
+mkdir -p "$MODULES"
+
+# test whether the module file is stored in union
+# if yes, then we must move it somewhere else (to RAM)
+unionctl --query "$MODULE" >/dev/null 2>&1
+if [ $? -eq 0 ]; then
+   echo "module file is stored inside the union, moving to $MODULES first..."
+   TARGET="$MODULES/`basename \"$MODULE\"`"
+   mv "$MODULE" "$TARGET"
+   if [ $? -ne 0 ]; then
+      echo "error copying module to memory, not enough free RAM? try df" >&2
+      rm "$TARGET"
+      return 2
+   fi
+   MODULE="$TARGET"
+fi
+
+MOD="`union_insert_module / \"$MODULE\" $IMAGES`"
+if [ $? -ne 0 ]; then echo "error inserting module to live filesystem" >&2; exit 3; fi
 
 # all executables in /etc/rc.d/ from this module will be started
 # with two arguments: "start" "mo". This happens only by this script (uselivemod),
