Added linux-live 6.0.6.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/initrd/linuxrc b/initrd/linuxrc
--- a/initrd/linuxrc
+++ b/initrd/linuxrc
@@ -1,4 +1,6 @@
 #!/bin/ash
+# Initial script for Linux Live operating system
+# Author: Tomas M <http://www.linux-live.org/>
 
 export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin
 . liblinuxlive
@@ -9,29 +11,35 @@ echolog "mounting /proc and /sys filesystems"
 mount -t proc proc /proc
 mount -t sysfs sysfs /sys
 ln -sf /proc/mounts /etc/mtab # this allows us to use umount -a
-mount -o remount,rw / # for the case we forgot rw boot option
+mount -o remount,rw /         # for the case we forgot rw boot option
 
 # use mdev to create /dev/ devices and setup it as a hotplug-handler
 mdev_start_hotplug
 
 # setup DEBUGCMD variable. If debug boot option is present, call debug()
-# function several times during script's execution
+# function several times during script's execution to help fighting bugs
 if [ "`cmdline_parameter debug`" ]; then DEBUGCMD="debug"; else DEBUGCMD=""; fi
 
 if [ "$DEBUGCMD" != "" ]; then
-   # debug must support USB keyboard as well
+   # debug prompt requires a keyboard. Including USB keyboards
    modprobe_usb_modules
 fi
 
 $DEBUGCMD
 
-# amount of RAM to store changes
+# Find out how much of RAM do we like to use to save filesystem changes
+# Defaults to 60%. Moreover it's not used if changes= boot argument exists.
 RAMSIZE="`cmdline_value ramsize`"
 if [ "$RAMSIZE" = "" ]; then RAMSIZE="60%"; fi
 
-# cdrom support, isofs support, aufs support, etc
+# Load essential drivers, like CDROM drivers, aufs/squashfs etc.
 modprobe_essential_modules
+
+# disable DMA if nodma parameter is used
 setup_dma
+
+# make sure ext3 partitions are not mounted using ext2 driver,
+# and vfat partitions are not mounted using msdos driver
 echo -e "ext3\next2\nvfat\n*" >/etc/filesystems
 
 mkdir -p $UNION
@@ -39,19 +47,68 @@ mkdir -p $MEMORY
 
 $DEBUGCMD
 
-echolog "setup directory for changes"
-CHANGESARG="`cmdline_value changes`"
-CHANGESPATH="`find_file $MOUNTDIR $CHANGESARG`"
-echolog $CHANGESPATH
+# Find livecd data directory
+echolog "looking for data directory"
 
-# if changes= argument is present, but we can't find specified file,
-# load USB modules and try again
-if [ "$CHANGESARG" != "" -a "$CHANGESPATH" = "" ]; then
-   modprobe_usb_modules
-   CHANGESPATH="`find_file $MOUNTDIR $CHANGESARG`"
+# First, try from= boot argument, if given
+DATAFROM="`cmdline_value from`"
+
+if [ "$DATAFROM" ]; then
+   DATAFROM="`find_file $MOUNTDIR $DATAFROM`"
+   if [ "$DATAFROM" = "" ]; then
+      # still empty? Load USB drivers and try again
+      modprobe_usb_modules
+      DATAFROM="`find_file $MOUNTDIR $DATAFROM`"
+   fi
+
+   if [ "$DATAFROM" ]; then
+      mount_device $DATAFROM $LOOPMOUNT # mount again, it may be loop device
+      if [ $? -eq 0 -a -f "$LOOPMOUNT/$LIVECDNAME" ]; then
+         echolog "found in $LOOPMOUNT"
+         DATA=$LOOPMOUNT/$LIVECDNAME
+      else
+         umount $LOOPMOUNT
+	 umount $MOUNTDIR/* 2>/dev/null
+      fi
+   fi
 fi
 
-mount_device $CHANGESPATH $MEMORY # if empty or failed, mount tmpfs:
+if [ "$DATA" = "" ]; then
+   # from= is not used or it didn't contain valid data
+   DATA="`find_file $MOUNTDIR $LIVECDNAME`"
+fi
+
+if [ "$DATA" = "" ]; then
+   # Still nothing found? Load USB modules and try again
+   modprobe_usb_modules
+   DATA="`find_file $MOUNTDIR $LIVECDNAME`"
+fi
+
+if [ "$DATA" = "" ]; then fatal \
+"$LIVECDNAME data not found.
+You are maybe using an unsupported boot device (eg. SCSI or PCMCIA CD-ROM).
+Workaround: Copy the directory $LIVECDNAME from your boot device to an IDE/SATA
+disk, eg. to /mnt/hda1/$LIVECDNAME or C:\\$LIVECDNAME. Then try to boot again."
+fi
+
+echolog "Using $LIVECDNAME data from $DATA"
+
+$DEBUGCMD
+
+echolog "setting up directory for changes"
+CHANGESVAL="`cmdline_value changes`"
+
+if [ "$CHANGESVAL" ]; then
+   CHANGESMNT="`find_file $MOUNTDIR $CHANGESVAL`"
+   if [ "$CHANGESMNT" = "" ]; then
+      # still empty? Load USB modules and try again
+      modprobe_usb_modules
+      CHANGESPATH="`find_file $MOUNTDIR $CHANGESVAL`"
+   fi
+   echolog $CHANGESMNT
+fi
+
+mount_device $CHANGESMNT $MEMORY # if empty or fails, mount tmpfs:
 if [ $? -ne 0 ]; then mount -t tmpfs -o "size=$RAMSIZE" tmpfs $MEMORY; fi
 
 # $UNION will be used as a root directory, livecd modules will be added soon
@@ -68,45 +125,6 @@ if [ $? -ne 0 ]; then fatal "can't setup union (aufs)"; fi
 
 $DEBUGCMD
 
-# try to find livecd data directory.
-echolog "looking for data directory"
-
-DATAFROM="`cmdline_value from`"
-DATAFROM="`find_file $MOUNTDIR $DATAFROM`"
-
-# when from= is used, search for liveCDdata.
-if [ "$DATAFROM" ]; then
-   mount_device $DATAFROM $LOOPMOUNT # we must mount again, if loop device
-   if [ $? -eq 0 -a -d "$LOOPMOUNT/$LIVECDNAME" ]; then
-      echolog "found in $LOOPMOUNT"
-      DATA=$LOOPMOUNT/$LIVECDNAME
-   fi
-fi
-
-if [ "$DATA" = "" ]; then
-   # from= is not used or it didn't contain liveCDdata
-   DATA="`find_file $MOUNTDIR $LIVECDNAME`"
-fi
-
-if [ "$DATA" = "" ]; then
-   # Still nothing found? Try USB devices
-   modprobe_usb_modules
-   DATA="`find_file $MOUNTDIR $LIVECDNAME`"
-fi
-
-$DEBUGCMD
-
-if [ "$DATA" = "" ]; then fatal \
-"LiveData not found. Searching for $LIVECDNAME directory.
-You are maybe using an unsupported boot device (eg. SCSI or PCMCIA CD-ROM)
-Try to copy the directory $LIVECDNAME from CD/USB to your IDE/SATA harddisk,
-for example to /mnt/sda1/ in Linux or C:\\ in Windos. Then boot again."
-fi
-
-echolog "Using $LIVECDNAME data from $DATA"
-
-$DEBUGCMD
-
 # If toram or copy2ram boot parameter is present, copy all fs modules to RAM.
 # (skip modules from /optional/ which are not listed in load= boot option)
 # Finaly modify DATA variable so it will point to correct directory
@@ -115,7 +133,7 @@ if [ "`cmdline_parameter toram`" != "" -o "`cmdline_parameter copy2ram`" != "" ]
    mkdir -p $COPY2RAM
 
    # make sure it's in RAM even with changes= parameter
-   if [ "$CHANGESPATH" ]; then mount -t tmpfs -o "size=$RAMSIZE" tmpfs $COPY2RAM; fi
+   if [ "$CHANGESMNT" ]; then mount -t tmpfs -o "size=$RAMSIZE" tmpfs $COPY2RAM; fi
    copy_to_ram $DATA $COPY2RAM
 
    cd_autoeject 1
