Added linux-live 5.0.14.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/initrd/linuxrc b/initrd/linuxrc
--- a/initrd/linuxrc
+++ b/initrd/linuxrc
@@ -31,25 +31,34 @@ setup_dma
 $DEBUGCMD
 
 # $UNION will be used as a root directory, livecd modules will be added soon.
-# Create temp filesystem and setup union on the top.
 echolog "setup union on $UNION"
 mkdir -p $UNION
 mkdir -p $MEMORY
-mount -t tmpfs -o "size=80%" tmpfs $MEMORY
+
+CHANGESDEV="`cmdline_value changes`"
+if [ "$CHANGESDEV" != "" ]; then
+   echo "mounting $CHANGESDEV to $MEMORY"
+   mount_device $CHANGESDEV $MEMORY
+else false; fi
+
+# mount tmpfs only in the case when changes= boot parameter was empty
+# or we were not able to mount the storage device
+if [ $? -ne 0 ]; then mount -t tmpfs -o "size=80%" tmpfs $MEMORY; fi
+
 mkdir -p $CHANGES
 mkdir -p $COPY2RAM
 mkdir -p $IMAGES
-mount -t unionfs -o dirs=$CHANGES unionfs $UNION
+mount -t unionfs -o dirs=$CHANGES=rw unionfs $UNION
+if [ $? -ne 0 ]; then fatal "can't setup union in /union directory"; fi
 
 $DEBUGCMD
 
 # try to find livecd data directory. If not found, try modprobing
-# USB or SCSI kernel modules and repead the find procedure again
+# USB kernel modules and repeat the find procedure again
 echolog "looking for data modules"
-if [ "$DATA" = "" ]; then DATA="`find_live_data_dir $UNION/$MOUNTDIR`"; fi
-if [ "$DATA" = "" ]; then modprobe_usb_modules;  DATA="`find_live_data_dir $UNION/$MOUNTDIR`"; fi
-if [ "$DATA" = "" ]; then modprobe_scsi_modules; DATA="`find_live_data_dir $UNION/$MOUNTDIR`"; fi
-if [ "$DATA" = "" ]; then fatal "Data for LiveCD not found"; fi
+DATA="`find_live_data_dir $MOUNTDIR`";
+if [ "$DATA" = "" ]; then modprobe_usb_modules; DATA="`find_live_data_dir $MOUNTDIR`"; fi
+if [ "$DATA" = "" ]; then fatal "Data for LiveCD not found. Are you using SCSI?"; fi
 echolog "found in $DATA"
 
 $DEBUGCMD
@@ -59,11 +68,12 @@ $DEBUGCMD
 # Finaly modify DATA variable so it will point to correct directory
 if [ "`cmdline_parameter toram`" != "" -o "`cmdline_parameter copy2ram`" != "" ]; then
    echolog "copying modules to RAM, this may take some time"
-   copy_modules $DATA $COPY2RAM
-   setup_cd_autoeject
+   copy_to_ram $DATA $COPY2RAM
+   cd_autoeject 1
    umount $DATA 2>/dev/null
    if [ $? -ne 0 ]; then umount `dirname $DATA` 2>/dev/null; fi
    DATA=$COPY2RAM
+   cd_autoeject 0
 fi
 
 mkdir -p $UNION/boot
@@ -75,6 +85,15 @@ $DEBUGCMD
 # to be mounted and inserted into live filesystem. Do it now.
 echolog "inserting all modules and creating live filesystem"
 union_insert_modules $UNION $DATA $IMAGES
+
+$DEBUGCMD
+
+echo "copying rootchanges"
+copy_rootchanges $DATA $UNION
+
+$DEBUGCMD
+
+echo "creating /etc/fstab"
 activate_fstab $UNION
 
 # More likely these directories aren't there.
diff --git a/tools/liblinuxlive b/tools/liblinuxlive
--- a/tools/liblinuxlive
+++ b/tools/liblinuxlive
@@ -41,9 +41,10 @@ header()
 fatal()
 {
    header "Fatal error occured - $1"
-   echolog "Something went wrong and we can't continue booting."
+   echolog "Something went wrong and we can't continue booting :("
    echolog "You may explore the system by using simple commands like ls, lsmod, mount, etc."
-   echolog "Finaly hit Ctrl+Alt+Delete to reboot."
+   echolog "You may also try to hit Ctrl+D. Booting will continue. Use at your own risk."
+   echolog "To be safe, hit Ctrl+Alt+Delete to reboot."
    echolog
    ash
 }
@@ -94,6 +95,7 @@ cmdline_value()
 #
 modprobe_module()
 {
+  if [ "$1" = "" ]; then return 1; fi
   PRINTK=`cat /proc/sys/kernel/printk`
   echo "0" >/proc/sys/kernel/printk
 
@@ -107,7 +109,7 @@ modprobe_module()
         gunzip -c $MODULE 2>/dev/null >$TMPMOD
         if [ "$?" -ne 0 ]; then cp $MODULE $TMPMOD; fi # can't gunzip? copy
         insmod $TMPMOD $2 >/dev/null 2>/dev/null; err=$?
-        if [ "$err" -eq 0 ]; then echo $TMPMOD >>$LSMOD; fi
+        if [ "$err" -eq 0 ]; then echo $TMPMOD >>$LSMOD; fi # module log
         rm $TMPMOD
      fi
   done
@@ -199,7 +201,8 @@ union_insert_module()
    while [ -e $TARGET ]; do TARGET=$TARGET.X; done
    mkdir -p $TARGET
    mount_module $2 $TARGET
-   union_insert_dir $1 $TARGET
+   if [ $? -ne 0 ]; then echo "can't read module data"; return 1; fi
+   union_insert_dir $1 $TARGET; 
 }
 
 # Insert all .mo modules, in $2 directory and subdirectories, to the union
@@ -210,6 +213,7 @@ union_insert_module()
 union_insert_modules()
 {
    list_modules $2 | while read MODULE; do
+      echo " -> `basename $MODULE`"
       union_insert_module $1 $MODULE $3
    done
 }
@@ -218,15 +222,19 @@ union_insert_modules()
 # $1 = data directory
 # $2 = target directory in RAM
 #
-copy_modules()
+copy_to_ram()
 {
-   list_modules $1 | while read MODULE; do
-      RELATIVE=${MODULE#$1}
-      DIR="`dirname $RELATIVE`"
-      mkdir -p $2/$DIR
-      cp $MODULE $2/$RELATIVE
-      if [ "$?" -ne 0 ]; then fatal "not enough memory to copy modules to RAM"; fi
-   done
+   cp -R $1/* $2
+   if [ "$?" -ne 0 ]; then fatal "can't copy to RAM, not enough memory?"; fi
+}
+
+# Copy content of "rootcopy" directory on the CD to $2 (union, usually)
+# $1 = source
+# $2 = destination
+#
+copy_rootchanges()
+{
+   cp -a $1/rootcopy/* $2 2>/dev/null # could be empty
 }
 
 # ===========================================================
@@ -277,11 +285,11 @@ list_block_devices()
 find_live_data_dir()
 {
    list_block_devices | while read DEVICE; do
-      DIR=$1/"`basename $DEVICE`"
-      mount_device $DEVICE $DIR;
+      DIR="/$1/`basename $DEVICE`"
+      mount_device $DEVICE $DIR
       if [ $? -ne 0 ]; then continue; fi
       FOUND=`ls -A1d $DIR/livecd.sgn $DIR/*/livecd.sgn 2>/dev/null | head -n 1`
-      if [ "$FOUND" = "" ]; then umount $DIR 2>/dev/null; rmdir $DIR 2>/dev/null;
+      if [ "$FOUND" = "" ]; then umount $DIR 2>/dev/null; rmdir $DIR 2>/dev/null
       else dirname "$FOUND"; return 1; fi
    done
 }
@@ -316,6 +324,13 @@ modprobe_essential_modules()
    modprobe_module squashfs
    echolog "starting unionfs support"
    modprobe_module unionfs
+   echolog "starting vfat support"
+   modprobe_module nls_cp437
+   modprobe_module nls_iso8859-1
+   modprobe_module nls_iso8859-2
+   modprobe_module vfat
+   echolog "starting ntfs support"
+   modprobe_module ntfs
    create_block_devices
 }
 
@@ -323,33 +338,22 @@ modprobe_essential_modules()
 #
 modprobe_usb_modules()
 {
-   echolog "starting USB support, this may take a while"
-   modprobe_module usb-storage
+   echolog "starting USB support"
    modprobe_module ehci-hcd
    modprobe_module ohci-hcd
    modprobe_module uhci-hcd
+   modprobe_module usb-storage
+   echolog "waiting for USB devices, max 9 seconds"
+   sleep 9
    create_block_devices
 }
 
-# modprobe kernel modules needed for SCSI disks
+# enable/disable CD autoejecting when unmounted
+# $1 = 1|0 ... enable|disable
 #
-modprobe_scsi_modules()
+cd_autoeject()
 {
-   echolog "starting SCSI support, this may take a while"
-   ls /lib/modules/`uname -r`/kernel/drivers/scsi | cut -d . -f 1 | while read MODULE; do
-      if [ "$MODULE" != "sg" -a "$MODULE" != "scsi_debug" ]; then
-         echolog "modprobe $MODULE..."
-	 modprobe_module $MODULE
-      fi
-   done
-   create_block_devices
-}
-
-# Enable CD autoejecting when unmounted
-#
-setup_cd_autoeject()
-{
-   echo 1 >/proc/sys/dev/cdrom/autoeject
+   echo $1 >/proc/sys/dev/cdrom/autoeject
 }
 
 # Disable DMA if nodma boot parameter is present
@@ -377,9 +381,9 @@ activate_fstab()
    echo "proc             /proc            proc        defaults         0   0" >>$FSTAB
 
    list_cdrom_devices | while read DEVICE; do
-      MOUNTDIR="/mnt/`basename $DEVICE`"
-      mkdir -p $MOUNTDIR
-      echo "$DEVICE $MOUNTDIR auto defaults,users 0 0" >>$FSTAB
+      MOUNTDIR="/mnt/cdrom_`basename $DEVICE`"
+      mkdir -p $1/$MOUNTDIR
+      echo "$DEVICE $MOUNTDIR iso9660 noauto,users 0 0" >>$FSTAB
    done
 
    list_partition_devices | while read DEVICE; do
@@ -387,7 +391,7 @@ activate_fstab()
       mount_device $DEVICE $1/$MOUNTDIR
       umount $1/$MOUNTDIR 2>/dev/null
       if [ $? -eq 0 ]; then # add to fstab only if mount+umount is OK
-         echo "$DEVICE $MOUNTDIR auto defaults,users 0 0" >>$FSTAB
+         echo "$DEVICE $MOUNTDIR auto auto,users,suid,dev,exec 0 0" >>$FSTAB
       else # remove empty directory
          rmdir $1/$MOUNTDIR 2>/dev/null
       fi
