Added linux-live 6.1.0.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -6,7 +6,7 @@
 
 export PATH=.:./tools:../tools:/usr/sbin:/usr/bin:/sbin:/bin:/
 
-CHANGEDIR="`dirname \`readlink -f $0\``"
+CHANGEDIR=$(dirname $(readlink -f $0))
 echo "Changing current directory to $CHANGEDIR"
 cd $CHANGEDIR
 
@@ -20,20 +20,20 @@ allow_only_root
 echo -ne "Name of your live distro [hit enter for $LIVECDNAME]: "
 read NEWLIVECDNAME
 if [ "$NEWLIVECDNAME" != "" ]; then LIVECDNAME=$NEWLIVECDNAME; fi
-LIVECDNAME="`echo $LIVECDNAME | tr -d ' '`"
+LIVECDNAME=$(echo $LIVECDNAME | tr -d ' ')
 
 . ./install
-if [ "$ROOT" ]; then 
+if [ "$ROOT" -a "$ROOT" != "/" ]; then 
    . ./install $ROOT
 fi
 
 # search for kernel
 VMLINUZ=$ROOT/boot/vmlinuz
-if [ -L "$VMLINUZ" ]; then VMLINUZ=`readlink -f $VMLINUZ`; fi
+if [ -L "$VMLINUZ" ]; then VMLINUZ=$(readlink -f $VMLINUZ); fi
 echo -ne "Enter path for the kernel you'd like to use [hit enter for $VMLINUZ]: "
 read NEWKERNEL
 if [ "$NEWKERNEL" != "" ]; then VMLINUZ="$NEWKERNEL"; fi
-if [ "`ls $VMLINUZ 2>>$DEBUG`" = "" ]; then echo "cannot find $VMLINUZ"; exit 1; fi
+if [ "$(ls $VMLINUZ 2>>$DEBUG)" = "" ]; then echo "cannot find $VMLINUZ"; exit 1; fi
 
 header "Creating LiveCD from your Linux"
 echo "some debug information can be found in $DEBUG"
