Added linux-live 6.2.8.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/tools/liblinuxlive b/tools/liblinuxlive
--- a/tools/liblinuxlive
+++ b/tools/liblinuxlive
@@ -105,9 +105,6 @@ fatal()
    echolog "Something went wrong and we can't continue. This should never happen."
    echolog "Please reboot your computer with Ctrl+Alt+Delete ..."
    echolog
-   umount -a -r -d 2>/dev/null
-   mount -t proc proc /proc
-   mount -t sysfs sysfs /sys
    ash < /dev/console
 }
 
@@ -143,6 +140,31 @@ cmdline_value()
    egrep -o "(^|[[:space:]])$1=[^[:space:]]+" /proc/cmdline | cut -d "=" -f 2- | tail -n 1
 }
 
+# Make sure the part of a script after 'mutex_lock' call is atomic,
+# that means the 'locked' part of the script can never be execuetd 
+# from several processes at the same time, in parallel.
+# Every script waits until it gathers the lock.
+# The lock directory is saved in /dev instead of /tmp, because /tmp may be
+# readonly at the time when the lock is needed (eg. when udev is starting)
+# $1 = name of the lock
+#
+mutex_lock()
+{
+   debug_log "mutex_lock" "$*"
+   while ! mkdir "/dev/ll-mutex-lock-$1" 2>/dev/null; do
+      usleep 100000;
+   done
+}
+
+# Unlock the lock so another waiting process can reusse it and continue
+# $1 = name of the lock
+#
+mutex_unlock()
+{
+   debug_log "mutex_unlock" "$*"
+   rmdir "/dev/ll-mutex-lock-$1" 2>/dev/null
+}
+
 # ===========================================================
 # system functions
 # ===========================================================
@@ -154,10 +176,14 @@ mount_initrd_loops()
    if [ -e /usr.lzm ]; then
       mount_device /usr.lzm /usr loop,ro squashfs
    fi
+   if [ -e /drivers.lzm ]; then
+      mount_device /drivers.lzm /lib/modules/*/kernel/drivers loop,ro squashfs
+   fi
 }
 
 # modprobe module $1, including all dependencies, suppress all messages
-# (own function because modprobe in busybox doesn't work with gzipped modules)
+# This was own function, because modprobe in busybox didn't support
+# neither gzipped modules nor dependencies. Seems to be fixed now, though.
 # $1 = module name, eg. ehci-hcd
 # $* = optional arguments
 #
@@ -165,7 +191,7 @@ modprobe_module()
 {
    debug_log "modprobe_module" "$*"
    local MODULE
-  
+
    MODULE="$1"
    shift
 
@@ -174,13 +200,14 @@ modprobe_module()
 }
 
 # mknod next loop device
-# - find biggest loop device in /dev/loop/
-# - mknod nearest bigger one.
-# - kernel must have support for it
+# - find biggest loop device in /dev/loop/, assume it to be used
+# - preallocate (mknod) 20 more loop devices in one round
 mknod_next_loop_dev()
 {
    debug_log "mknod_next_loop_dev" "$*"
-   local NR PFX
+   local i NR END PFX
+
+   mutex_lock mknod_next_loop_dev
 
    if [ -d /dev/loop ]; then
       NR=$(find /dev/loop/ -maxdepth 1 | sed -r 's/[^0-9]+//' | sort -n | tail -n 1)
@@ -190,8 +217,13 @@ mknod_next_loop_dev()
       PFX=""
    fi
    NR=$(expr 0$NR + 1)
-   mknod /dev/loop$PFX$NR b 7 $NR 2>/dev/null
+   END=$(expr 0$NR + 20)
+   for i in $(seq $NR $END); do
+      mknod /dev/loop$PFX$i b 7 $i 2>/dev/null
+   done
    echo /dev/loop$PFX$NR
+
+   mutex_unlock mknod_next_loop_dev
 }
 
 # ===========================================================
@@ -259,6 +291,7 @@ iocharset()
 # $1 = filesystem
 # $2 = 'fstab' or 'mount' ... 'auto'/'noauto' string is enabled (fstab) or disabled (mount)
 #
+
 fs_options()
 {
    debug_log "fs_options" "$*"
@@ -267,13 +300,20 @@ fs_options()
    NOAUTO=$(cmdline_parameter noauto)
    if [ "$NOAUTO" = "" ]; then NOAUTO="auto"; fi
    if [ "$2" = "fstab" ]; then echo -n "$NOAUTO," ; fi
-   if [ "$1" = "swap" ]; then echo "defaults"; return 0; fi
+   if [ "$1" = "swap" ]; then echo "defaults,pri=1"; return 0; fi
    echo -n "noatime,users,suid,dev,exec"
 
    IOCHARSET=$(iocharset)
 
    if [ "$1" = "vfat" ]; then
       echo -n ",quiet,umask=0,check=s,shortname=mixed"
+      if [ "$IOCHARSET" ]; then
+         echo ",iocharset=$IOCHARSET"
+      fi
+   fi
+
+   if [ "$1" = "iso9660" ]; then
+      echo -n ",ro"
       if [ "$IOCHARSET" ]; then
          echo ",iocharset=$IOCHARSET"
       fi
@@ -300,8 +340,24 @@ device_filesystem()
    debug_log "device_filesystem" "$*"
    local NTFS
 
-   if [ -e /usr/bin/ntfsmount ]; then NTFS="ntfs-3g"; else NTFS="ntfs"; fi
+   if [ -e /bin/ntfsmount ]; then NTFS="ntfs-3g"; else NTFS="ntfs"; fi
    blkid -s TYPE "$1" -o value | sed "s/msdos/vfat/" | sed "s/ntfs/$NTFS/"
+}
+
+# tell us if the given filesystem is supported
+# (eg. it's in /proc/filesystems or we know it)
+# $1 = filesystem name
+#
+is_supported_filesystem()
+{
+   debug_log "is_supported_filesystem" "$*"
+
+   if [ -e /bin/ntfsmount -a "$1" = "ntfs-3g" ]; then
+      return 0
+   fi
+
+   # the following command will set the return value
+   egrep -q "[[:space:]]$1\$" /proc/filesystems
 }
 
 # Mount device $1 to $2
@@ -339,11 +395,13 @@ mount_device()
    fi
 
    # not enough loop devices? try to create one.
-   # This will work only with newest kernels. Tested with 2.6.23.
    if [ $ERR -eq 2 ]; then
        LOOPDEV=$(mknod_next_loop_dev)
        OPTIONS=$(echo "$OPTIONS" | sed -r "s/,loop//g")
-       losetup "$LOOPDEV" "$DEV" 2>/dev/null
+       losetup "$LOOPDEV" "$DEV" 2>/dev/null # busybox's losetup doesn't support -r
+       if [ $? -ne 0 ]; then
+          losetup -r "$LOOPDEV" "$DEV" 2>/dev/null # force read-only in case of error
+       fi
        mount -n -o $OPTIONS $FS "$LOOPDEV" "$2" >/dev/null 2>&1
        ERR=$?
    fi
@@ -406,7 +464,8 @@ create_module()
    rm -f "$2" # overwrite, never append to existing file
    mksquashfs "$1" "$2" -b 256K -lzmadic 256K $3 $4 $5 $6 $7 $8 $9>/dev/null
    if [ $? -ne 0 ]; then return 1; fi
-   chmod oga-wx "$2" # remove execute attrib
+   chmod a-wx "$2" # remove execute and write attrib
+   chmod a+r "$2" # add read for everyone
 }
 
 # ismountpoint exits with 0 if $1 is mountpoint, else exits with 1
@@ -448,6 +507,7 @@ union_insert_dir()
 #
 find_modules()
 {
+   debug_log "find_modules" "$*"
    find "$1/base" "$1/modules" "$1/optional" -name "*.lzm" 2>/dev/null | sort
 }
 
@@ -533,6 +593,27 @@ copy_to_ram()
 # discovery functions
 # ===========================================================
 
+# List all supported network drivers
+#
+list_network_drivers()
+{
+   debug_log "list_network_drivers" "$*"
+
+   # these drivers are probed in Slackware's initrd
+   # (see initrd.img/scripts/network.sh).
+   # I don't have personal experiences with most of these drivers
+   # so I'll be happy if you report any particular one to be not working
+   # (eg. causing hangups) in order to remove it from this list.
+
+   echo 3c59x acenic atl1 de4x5 dgrs eepro100 e1000 epic100 hp100 ne2k-pci \
+   olympic pcnet32 r8169 rcpci 8139too 8139cp sktr skge sky2 tulip via-rhine \
+   yellowfin tg3 dl2k ns83820 depca ibmtr 3c501 3c503 3c505 3c507 3c509 3c515 \
+   ac3200 acenic at1700 cosa cs89x0 de4x5 de600 de620 e2100 eepro eexpress \
+   es3210 eth16i ewrk3 fmv18x forcedeth hostess_sv11 hp-plus hp lne390 ne3210 \
+   ni5010 ni52 ni65 sb1000 sealevel smc-ultra sis900 smc-ultra32 smc9194 wd \
+   | tr " " "\n"
+}
+
 # List all CD-ROMs
 # by using /proc entries
 #
@@ -566,6 +647,9 @@ list_partition_devices()
    debug_log "list_partition_devices" "$*"
    if [ "$(cmdline_parameter nohd)" != "" ]; then return 1; fi
    cat /proc/partitions | grep -v loop | grep -v major | grep -v '^$' | sed -r "s:^[0-9 ]+:/dev/:"
+   if [ -e /dev/mapper/control ]; then # list LVM partitions if available
+      ls -1 /dev/mapper/ | grep -v "^control\$" | sed -r "s:^:/dev/mapper/:"
+   fi
 }
 
 # List all disk devices
@@ -717,6 +801,34 @@ find_in_computer()
    echo $RESULT
 }
 
+# Find and run all scripts from the given module
+# This function is used by the activate and deactivate script when the distro
+# is already started, not during live setup
+# $1 = mounted module full path
+# $2..$n = optional arguments for the scripts, eg. 'start'
+#
+find_n_run_scripts()
+{
+   debug_log "find_n_run_scripts" "$*"
+   local MOD
+
+   MOD="$1"
+   shift
+
+   if [ -d $MOD/etc/rc.d -o -d $MOD/etc/rc.d/init.d -o -d $MOD/etc/init.d ]; then
+      ( find $MOD/etc/rc.d -type f -maxdepth 1 2>/dev/null ; \
+        find $MOD/etc/init.d -type f -maxdepth 1 2>/dev/null  ; \
+        find $MOD/etc/rc.d/init.d -type f -maxdepth 1 2>/dev/null \
+      ) | cut -b ${#MOD}- | cut -b 2- | xargs -n 1 -r readlink -f | sort -u | while read SCRIPT; do
+         if [ "$SCRIPT" != "" -a -x "$SCRIPT" -a ! -d "$SCRIPT" ]; then
+            # call the script by real path, not from the module
+            log "starting '$SCRIPT $@'"
+            ${SCRIPT} "$@"
+         fi
+      done
+   fi
+}
+
 # ===========================================================
 # hardware preparation functions
 # ===========================================================
@@ -802,15 +914,67 @@ modprobe_pcmcia_modules()
    modprobe_module yenta_socket
 }
 
-# Unload all modules loaded to kernel which are not used
-# (currently used modules will be silently ignored)
+# Load network drivers unless eth[0-9] is found
+#
+modprobe_network_modules()
+{
+   debug_log "modprobe_network_modules" "$*"
+   local ETH
+
+   # skip module loading if nohotplug bootparam is present
+   if [ "$(cmdline_parameter nohotplug)" ]; then return 0; fi
+
+   # probe all drivers. Start by the ones mentioned in pcimodules' output
+   for module in $(list_network_drivers | egrep "$(pcimodules | tr "\n" "|")!") $(list_network_drivers); do
+      modprobe_module $module
+      ETH=$(cat /proc/net/dev | grep : | grep -v lo: | cut -d : -f 1 | tr -d " ")
+      if [ "$ETH" != "" ]; then
+         echo $ETH
+         return 0
+      fi
+      rmmod $module 2>/dev/null
+   done
+}
+
+# Start udhcpc to get IP address from DHCP server
+# $1 = interface to use (optional)
+#
+init_dhcp()
+{
+   debug_log "start_dhcp_client" "$*"
+
+   if [ "$1" != "" ]; then
+      ifconfig $1 up
+      udhcpc -i $1 -q
+   else
+      ifconfig eth0 up
+      udhcpc -q
+   fi
+}
+
+# Mount http filesystem from the given server
+# $1 = server
+# $2 = mountdir
+#
+mount_httpfs()
+{
+   debug_log "mount_httpfs" "$*"
+
+   mkdir -p $2
+   httpfs $1 $2
+}
+
+
+# Unload modules loaded to kernel which are not used
+# This function used to unload more modules, but it may cause
+# problems to auto-remove some of them (eg. a network module 
+# can seem unneeded even if network is to be used very soon.
 #
 rmmod_unused_modules()
 {
    debug_log "rmmod_unused_modules" "$*"
    rmmod usb-storage uhci-hcd ohci-hcd ehci-hcd 2>/dev/null
    rmmod yenta_socket rsrc_nonstatic pcmcia pcmcia_core 2>/dev/null
-   rmmod $(cat /proc/modules | cut -d " " -f 1) 2>/dev/null
 }
 
 # kill all unneeded processes, which have bigger PID then the PID of
@@ -866,13 +1030,17 @@ dev_is_in_fstab()
 fstab_add_line()
 {
    debug_log "fstab_add_line" "$*"
+   local DIR
+
+   if [ "$4" != "swap" ]; then DIR="$3"; else DIR="none"; fi
    if ! dev_is_in_fstab "$1" "$2"; then
-      echo "$2" "$3" "$4" "$5" 0 0 "$FSTABLLFLAG" >>$1
+      echo "$2" "$DIR" "$4" "$5" 0 0 "$FSTABLLFLAG" >>$1
    fi
 }
 
 # create correct fstab file in $1/etc/fstab and create apropriate
-# mount directories in $1/mnt.
+# mount directories in $1/mnt. This function is only calld once,
+# during liveCD startup (even before init from the distro is started).
 # $1 = root directory (union)
 #
 fstab_update()
@@ -886,25 +1054,31 @@ fstab_update()
    cat $FSTAB 2>/dev/null | grep -v "$FSTABLLFLAG" >$FSTABTMP
 
    fstab_add_line $FSTABTMP aufs / aufs defaults
-   fstab_add_line $FSTABTMP devpts /dev/pts devpts gid=5,mode=620
    fstab_add_line $FSTABTMP proc /proc proc defaults
    fstab_add_line $FSTABTMP sysfs /sys sysfs defaults
+   fstab_add_line $FSTABTMP devpts /dev/pts devpts gid=5,mode=620
+   fstab_add_line $FSTABTMP tmpfs /dev/shm tmpfs defaults
+
    list_cdrom_devices | while read DEVICE; do
       MNT=$(device_mountdir $DEVICE)
       FS=$(device_filesystem $DEVICE)
       if [ "$FS" = "" ]; then FS=iso9660; fi
       mkdir -p "$1/$MNT"
-      fstab_add_line $FSTABTMP $DEVICE $MNT $FS noauto,users,exec
+      fstab_add_line $FSTABTMP $DEVICE $MNT $FS $(fs_options $FS fstab)
    done
    list_partition_devices | while read DEVICE; do
       MNT=$(device_mountdir $DEVICE)
       FS=$(device_filesystem $DEVICE)
       OPT=$(fs_options $FS fstab)
 
-      # if the partition has filesystem, add it to fstab
-      if [ "$FS" != "" ]; then
+      if [ "$FS" = "swap" ]; then
          fstab_add_line $FSTABTMP $DEVICE $MNT $FS $OPT
-         if [ "$FS" != "swap" ]; then mkdir -p "$1/$MNT"; fi
+      fi
+
+      # If the partition has a valid filesystem, add it to fstab
+      if is_supported_filesystem "$FS"; then
+         fstab_add_line $FSTABTMP $DEVICE $MNT $FS $OPT
+         mkdir -p "$1/$MNT"
       fi
    done
 
