Added linux-live 5.0.16.
Signed-off-by: Christopher Rogers <slaxemulator@gmail.com>

diff --git a/tools/uselivemod b/tools/uselivemod
--- a/tools/uselivemod
+++ b/tools/uselivemod
@@ -18,6 +18,13 @@ else
 fi
 
 union_insert_module / "$1" /mnt/live/memory/images 2>/dev/null
+if [ $? -ne 0 ]; then
+   MODULE=/mnt/live/memory/copy2ram/`basename $1`
+   while [ -a "$MODULE" ]; do MODULE="$MODULE.x"; done
+   echo "error occured. copying module to $MODULE and trying again"
+   cp $1 $MODULE
+   union_insert_module / "$MODULE" /mnt/live/memory/images 2>/dev/null
+fi
 
 # executable in /var/log/setup/setup.modulename will be started
 # only by this script (uselivemod)
